const Quotes = [
  `"Great victory requires great risk." - Rick Riordan`,
  `"Tomorrow’s victory is today’s practice." - Chris Bradford`,
  `"Silence is the warrior’s art — and meditation is his sword. With it, you’ll cut through your illusions." - Dan Millman`,
  `"Any great warrior is also a scholar, and a poet, and an artist." - Steven Seaga`,
  `"Luck is simply the advantage a true warrior gains in excuting the correct course of action." - R.A. Salvatore`,
  `"No one's born to be a warrior, no one born an average man. We made one or the other and we try to understand, try to understand." - Zac Brown Band`,
  `"A true warrior in crypto never gives up, unless it’s a smart move." - Shark`,
  `"You may have to fight a battle more than once to win it." - Margaret Thatcher`,
  `"I realized a long time ago that a warrior in search of his dream must take his inspiration from what he actually does & not from what he imagines himself doing." - Paulo Coelho`,
  `"All men die, but not all men really live." - William Wallace`,
  `"It’s natural to feel fear. All great warriors are afraid. Only the stupid and the delusional are not." - Rick Riordan`,
  `"A warrior’s greatest enemy can also be his greatest teacher." - Taran Matharu`,
  `"I am not afraid of an army of lions led by sheep: I am afraid of an army of sheep led by a lion." - Alexander The Great`,
  `"Perseverance is failing 19 times and succeeding the 20th." - Julie Andrews Edwards`,
  `"To lead your legions to victory, you need to plan ahead and predict what could happen." - Shark`,
  `"Let your plans be dark and as impenetrable as night, and when you move, fall like a thunderbolt." - Sun Tzu`,
  `"History has remembered the kings and warriors, because they destroyed; art has remembered the people, because they created." - William Morris`,
  `"The warrior must never get angry in war." - Lailah Gifty Akita`,
  `"The best fighter is never angry." - Lao Tzu`,
  `"There are no shortcuts to any place worth going." - Beverly Sills`,
  `"Some Warriors look fierce, but are mild. Some seem timid, but are vicious. Look beyond appearances; position yourself for the advantage."   - Deng Ming-Dao`,
  `"Great warriors, like great earthquakes, are principally remembered for the mischief they have done." - Christian Nestell Bovee`,
  `"The two most powerful warriors are patience and time." - Leo Tolstoy`,
  `"Crypto can have a dip, but a strong warrior never dumps his sword." - Shark`,
  `"And now, born from the ashes, she’s a warrior in bloodied black." - Amie Kaufman`,
  `"The successful warrior is the average man with laser-like focus." - Bruce Lee`,
  `"Your mind is a battlefield, be its commander, not its soldier." - Unknown source`,
  `"Weakness is strong. I must be stronger." - Jocko Willink`,
  `"To be heroic is to be courageous enough to die for something; to be inspirational is to be crazy enough to live a little." - Criss Jami`,
  `"A true warrior fights not because he hates what is in front of him, but because he loves what is behind him." - G.K. Chesterton`,
  `"The true soldier fights not because he hates what is in front of him, but because he loves what is behind him." - G.K. Chesterton`,
  `"I do what I do because it is the right thing to do. I am a warrior, and it is the way of the warrior to fight superior odds." - Paul Watson`,
  `"Warriors are like sharks. They never really sleep, and are always ready for battle." - Shark`,
  `"I am a warrior not because I always win but because I will always fight." - Unknown source`,
  `"Life can sometimes get the best of you but your state of mind determines your outcome." - Sanjo Jendayi`,
  `"Warriors do not win victories by beating their heads against the walls, but by overtaking the walls. Warriors jump over walls; they don't demolish them." - Carlos Castaneda`,
  `"The only thing a warrior cannot fight is her own fierce nature." - Bianca Marais`,
  `"A warrior must only take care that his spirit is never broken." - Shissai`,
  `"I’m a warrior when it comes to pursuing roles." - Daniel Day-Lewis`,
  `"If you’re a true warrior, competition doesn’t scare you. It makes you better." - Andrew Whitworth`,
  `"Go to the battlefield firmly confident of victory and you will come home with no wounds whatsoever." - Uesugi Kenshin`,
  `"The warrior stands, ready to defend, ready to fight for those he serves. He is a warrior of virtue, A knight of conscience. He is who we all wish to be." - Anthony Hincks`,
  `"In the privacy of my dreams, I’m a warrior." - Kimberly Derting`,
  `"Do not pray for an easy life, pray for the strength to endure a difficult one." - Bruce Lee`,
  `"A warrior knows that the ends do not justify the means. Because there are no ends, there are only means." - Paulo Coelho`,
  `"All of old. Nothing else ever. Ever tried. Ever failed. No matter. Try again. Fail again. Fail better." - Samuel Beckett`,
  `"Did you ever hear a real warrior fud? I didn’t." - Shark`,
  `"To hold it together when everyone else would understand if you fell apart, that’s true strength." - Miyamoto Musashi`,
  `"Cowards shrink from challenges, weaklings flee from them, but warriors wink at them." - Matshona Dhliwayo`,
  `"When you become fully responsible for your life, you can become fully human; once you become human, you may discover what it means to be a warrior." - Dan Millman`,
  `"A warrior has to believe, for his belief is an essential part of his being." - Theun Mares`,
  `"Victorious warriors draw their strength from the highest source; their love." - Tapan Ghosh`,
  `"I don’t know how I’m going to win, I just know I’m not going to lose." - Gokham Saki`,
  `"And, though the warrior's sun has set, its light shall linger round us yet, bright, radiant, blest." - Jorge Manrique`,
  `"It gives me strength to have somebody to fight for; I can never fight for myself, but, for others, I can kill." - Emilie Autumn`,
  `"A warrior cannot lower his head – otherwise he loses sight of the horizon of his dreams." - Paulo Coelho`,
  `"One by one she slew her fears, and then planted a flower garden over their graves." - John Mark Green`,
  `"A warrior must believe in his strength of will, of purpose, of heart and soul." - David Gemmell`,
  `"A warrior never worries about his fear." - Carlos Castaneda`,
  `"The Spartans do not ask how many are the enemy but where are they." - Plutarch`,
  `"Never strike out of anger if, at all possible, this will give your enemy the advantage and strengthen his resolve and psyche." - Soke Behzad Ahmadi`,
  `"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all." - Dale Carnegie`,
  `"Our greatest glory is not in never falling, but in rising every time we fall." - Confucius`,
  `"A warrior with a cause is the most dangerous soldier of all." - Michael Scott`,
  `"The only reason a warrior is alive is to fight, and the only reason a warrior fights is to win." - Miyamoto Musashi`,
  `"The path of a warrior is lifelong, and mastery is often simply staying on the path." - Richard Strozzi-Heckler`,
  `"The strength of a warrior is not defined by the wars he wins; but the times he seeks for peace." - Aniket S. Sharma`,
  `"An action committed in anger is an action doomed to failure." - Genghis Khan`,
  `"During times of persistent hardship is when the warrior learns the most about his fortitude." - Bodhi Sanders`,
  `"Take a chance and risk it all or play it safe and suffer defeat." - Pittacus Lore`,
  `"Discipline is your best friend. It will take of you like nothing else can." - Jocko Willink`,
  `"It’s not how we fall. It’s how we get back up again." - Patrick Ness`,
  `"Difficulties strengthen the mind, as labor does the body." - Lucius Annaeus Seneca`,
  `"Warriors don't raise to the level of expectations, they fall to the level of their training." - Archilochus`,
  `"We don’t rise to the level of our expectations, we fall to the level of our training." - Archilochus`,
  `"All men are warriors. And life for everything in our universe is nothing but war." - David Zindell`,
  `"Before you can see the Light, you have to deal with the darkness." - Dan Millman`,
  `"A warrior may change his metal, but not his heart." - Edgar Rice Burroughs`,
  `"The warrior that has the most confidence in his abilities to fight is usually the most humble person you will ever meet." - Terry Bryan`,
  `"To win any battle, you must fight as if you are already dead." - Miyamoto Musashi`,
  `"A warrior lives by acting, not by thinking about acting, nor by thinking about what he will think he has finished acting." - Carlos Castaneda`,
  `"A warrior's greatest glory is not in never falling, but in rising every time we fall." - Confucius`,
  `"For a warrior it is not enough to win a war; it is more important to organize the peace." - Aristotle`,
  `"A Warrior of Light does not postpone making decisions."- Paulo Coelho`,
  `"Dripping water hollows out stone, not through force but through persistence." - Ovid`,
  `"Ideas are the great warriors of the world, and a war that has no idea behind it, is simply a brutality." - James A. Garfield`,
  `"This is the strange way of the world, that people who simply want to love are instead forced to become warriors." - Lauren Oliver`,
  `"You should reach the limits of virtue before you cross the border of death." - Aristodemus, Spartan Warrior`,
  `"Never underestimate the vital importance of finding early in life the work that for you is play. This turns possible underachievers into happy warriors." - Ken Robinson`,
  `"I know what I’m capable of; I am a soldier now, a warrior, I am someone to fear, not hunt." - Pittacus Lore`,
  `"It is better to die on your feet than to live on your knees." - Emiliano Zapata`,
  `"Every warrior wants a worthy opponent. There is no redress in fighting the pathetic." - Donna Lynn Hope`,
  `"Protecting yourself is self-defense. Protecting others is warriorship." - Bodhi Sanders`,
  `"Some must be warriors, that others may live in peace." - Mercedes Lackey`,
  `"Warriors train, everyone else works out." - Lahong Guro Earles`,
  `"Never lose hope. Storms make people stronger and never last forever." - Roy T. Bennett`,
  `"Warriors of light are not perfect. Their beauty lies in accepting this fact and still desiring to grow and to learn." - Paulo Coelho`,
  `"You cannot expect victory and plan for defeat." - Joel Osteen`,
  `"Toil and risk are the price of glory, but it is a great thing to live with courage and die leaving an everlasting fame." - Alexander The Great`,
  `"A warrior seeks to act rather than talk." - Carlos Castaneda`,
  `"A true warrior, like tea, shows his strength in hot water." - Unknown source`,
  `"Warriors should suffer their pain silently." - Erin Hunter`,
  `"One mark of a great soldier is that a great soldier fights on his own terms or fights not at all." - Sun Tzu`,
  `"A few fly bites cannot stop a spirited horse." - Mark Twain`,
  `"Every victorious warrior draws his strength from the highest source; his love." - Tapan Ghosh`,
  `"Courage is not having the strength to go on; it is going on when you don’t have the strength." - Theodor Roosevelt`,
  `"If a warrior is to succeed at anything, the success must come gently, with a great deal of effort but with no stress or obsession." - Carlos Castaneda`,
  `"But where life is more terrible than death, it is then the truest valor to dare to live." - Inazo Nitobe`,
  `"Better to fight and fall than to live without hope." - Volsunga`,
  `"There is no greater warrior than a mother protecting her child." - N.K. Jemisin`,
  `"Strategy is the craft of the warrior." - Miyamoto Musashi`,
  `"Out of suffering have emerged the strongest souls; the most massive characters are seared with scars." - Kahlil Gibran`,
  `"He who conquers himself is the mightiest warrior." - Confucius`,
  `"Courage, above all things, is the first quality of a warrior." - Karl von Clausewitz`,
  `"The essence of warriorship, or the essence of human bravery, is refusing to give up on anyone or anything." - Chogyam Trungpa`,
  `"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win." - Sun Tzu`,
  `"Warriors want a worthy opponent. There is no redress in fighting the pathetic." - Donna Lynn Hope`,
  `"Warriors do not argue, but they take decisions." - Chukwuemeka E.O`,
  `"Some of the most beautiful things worth having in your life come wrapped in a crown of thorns." - Shannon L. Alder`,
  `"I found an inner strength to fight for myself. It was clear that nobody else would." - Tehmina Durrani`,
  `"A warrior who is prepared to fight must also be prepared to die." - Sun Tzu`,
  `"The average man is hooked to his fellow men, while the warrior is hooked only to infinity." - Carlos Castaneda`,
  `"The true warrior isn’t immune to fear. She fights in spite of it." - Francesca Lia Block`,
  `"The greatest warriors know when to retreat." - Maureen Joyce Connolly`,
  `"Warriors do not lower themselves to the standards of other people; they live independently; according to their own standards and code of conduct." - Bohdi Sanders`,
  `"Every great warrior must learn to endure and overcome the adversities of life." - Lailah Gifty Akita`,
  `"Every person has the power to change their fate if they are brave enough to fight for what they desire more than anything." - Stephanie Garber`,
  `"To be a warrior is to learn to be genuine in every moment of your life." - Chogyam Trungpa`,
  `"You are a warrior! Built to endure. Able to conquer. Nothing can hold you down." - Beatrice Garrett`,
  `"He who sweats more in training bleeds less in war." - Spartan Warrior Creed`,
  `"The more you sweat in training, the less you bleed in combat." - Richard Marcinko`,
  `"A warrior does not give up what he loves, he finds the love in what he does." - Dan Millman`,
  `"Winning is not everything, but wanting to win is." - Vince Lombardi`,
  `"Consider your goal like a war to win and use whatever strategies you know to win." - Bangambiki Habyarimana`,
  `"Fear doesn’t go away. The warrior and the artist live by the same code of necessity, which dictates that the battle must be fought anew every day." - Steven Pressfield`,
  `"The art of being a warrior is to balance the wonder and the terror of being alive." - Carlos Castaneda`,
  `"The big difference between a warrior and a victim is that the victim represses and the warrior refrains." - Don Miguel Rui`,
  `"Competition doesn't scare a true warrior, it makes him better." - Andrew Whitworth`,
  `"Never forget about your inner warrior; sometimes she’s all you have" - Mozelle Barr Martin`,
  `"We chose whether to be warriors or to be ordinary." - Carlos Castaneda`,
  `"Surprise is the warrior’s greatest weapon." - Erin Hunter`,
  `"Victory is reserved for those who are willing to pay its price." - Sun Tzu`,
  `"Nothing can resist a human will that will stake its very existence on its purpose." - Benjamin Disraeli`,
  `"The struggles we endure today will be the ‘good old days’ we laugh about tomorrow." - Aaron Lauritsen`,
  `"Warriors use their intent and will to shape their lives. All of their actions are conscious, intentional, and complete." - Kerr Cuhulain`,
  `"A cowardly man thinks he will ever live, if warfare he avoids; but old age will give him no peace, though spears may spare him." - Havamal`,
  `"It is not enough to win war; it is more important to organize the peace." - Aristotle`,
  `"Never confuse a single defeat with a final defeat." - F. Scott Fitzgerald`,
  `"Be ashamed to die until you have won some victory for humanity." - Horace Mann`,
  `"Don’t let hollow heroes distract you from saving yourself."- Nikki Rowe`,
  `"You never know how strong you are, until being strong is your only choice." - Bob Marley`,
  `"The fight isn’t over until you win." - Robin Hobb`,
  `"You’re trying to escape from your difficulties, and there never is any escape from difficulties, never. They have to be faced and fought." - Enid Blyton`,
  `"There is nothing outside of yourself that can ever enable you to get better, stronger, richer, quicker, or smarter. Everything is within." - Miyamoto Musashi`
  ]
  
export default Quotes
