export const translations = {
  logo: {
    en: "Logo",
    es: "Logotipo",
    cn: "标识",
    pt: "Logotipo",
    tr: "Logo",
    ru: "Логотип",
    fr: "Logo",
    de: "Logo",
    pl: "Logo",
    ph: "Simbolo",
  },
  claim: {
    en: "Claim",
    es: "Reclamar",
    cn: "领取",
    pt: "Resgatar",
    tr: "Iddia",
    ru: "претензия",
    fr: "Prétendre",
    de: "Claim",
    pl: "Odbierz",
    ph: "Kunin",
  },
  bloodstone: {
    en: "Bloodstone",
    es: "Bloodstone",
    cn: "Bloodstone",
    pt: "Bloodstone",
    tr: "Bloodstone",
    ru: "Bloodstone",
    fr: "Bloodstone",
    de: "Bloodstone",
    pl: "Bloodstone",
    ph: "Bloodstone",
  },
  summonBeast: {
    en: "Summon Beasts",
    es: "Invocar Bestias",
    cn: "召唤兽",
    pt: "Invocar Besta",
    tr: "Canavarları Çağır",
    ru: "Призвать зверя",
    fr: "Invoquer bête",
    de: "Roep Beesten op",
    pl: "Przyzwanie bestii",
    ph: "Magtawag ng Hayop",
  },
  summonQuantity: {
    en: "Summon Quantity",
    es: "Cantidad de invocación",
    cn: "召唤数量",
    pt: "Quantidade de Invocação",
    tr: "Çağırma Miktarı",
    ru: "Количество призыва",
    fr: "Quantité d'invocation",
    de: "Hoeveelheid van Aanroeping",
    pl: "Ilość przywołań",
    ph: "Dami ng ipatawag",
  },
  currentBeasts: {
    en: "Current Beasts",
    es: "Bestias actuales",
    cn: "当前的野兽",
    pt: "Bestas Atuais",
    tr: "Mevcut Canavarlar",
    ru: "Текущие звери",
    fr: "Bêtes actuelles",
    de: "Huidige Beesten",
    pl: "Obecne bestie",
    ph: "Kasalukuyang mga Hayop",
  },
  warriorCapacity: {
    en: "Total Capacity of All Beasts",
    es: "Capacidad máxima de guerreros",
    cn: "最大勇士总数量",
    pt: "Capacidade Máxima Total de Guerreiros",
    tr: "Toplam Maksimum Savaşçı Kapasitesi",
    ru: "Общая максимальная вместимость воинов",
    fr: "Capacité totale maximale des guerriers",
    de: "Maximum capaciteit van Gerreros ",
    pl: "Maksymalna pojemność wszystkich wojowników",
    ph: "Kabuuang Kapasidad ng mga Mandirigma",
  },
  filterCapacity: {
    en: "Filter By Capacity",
    es: "Filtrar por capacidad",
    cn: "按容量过滤",
    pt: "Filtrar por Capacidade",
    tr: "Kapasiteye Göre Filtrele",
    ru: "Фильтровать по емкости",
    fr: "Filtrer par capacité",
    de: "Filteren op capaciteit",
    pl: "Filtruj według pojemności",
    ph: "Salain Ayon sa Kapasidad",
  },
  all: {
    en: "All",
    es: "Todo",
    cn: "全部",
    pt: "Tudo",
    tr: "Her şey",
    ru: "Все",
    fr: "Tout",
    de: "Alle",
    pl: "Wszystkie",
    ph: "Lahat",
  },
  welcome: {
    en: "Nadodo is watching",
    es: "Nadodo está mirando",
    cn: "纳多多在看",
    pt: "Nadodo está assistindo",
    tr: "Nadodo izliyor",
    ru: "Надодо наблюдает",
    fr: "Nadodo regarde",
    de: "Nadodo kijkt",
    pl: "Nadodo patrzy",
    ph: "Nanunuod si Nadodo",
  },
  play: {
    en: "Play",
    es: "Jugar",
    cn: "玩",
    pt: "Jogar",
    tr: "Oyna",
    ru: "играть",
    fr: "Jouer",
    de: "Speel",
    pl: "Graj",
    ph: "Maglaro",
  },
  market: {
    en: "Market",
    es: "Mercado",
    cn: "市场",
    pt: "Mercado",
    tr: "Market",
    ru: "Рынок",
    fr: "Marché",
    de: "Markt",
    pl: "Rynek",
    ph: "Pamilihan",
  },
  howToPlay: {
    en: "How To Play",
    es: "Cómo Jugar",
    cn: "怎么玩",
    pt: "Como jogar",
    tr: "Nasıl oynanır",
    ru: "Как играть",
    fr: "Comment jouer",
    de: "Hoe te spelen",
    pl: "Jak grać",
    ph: "Paano laruin",
  },
  social: {
    en: "Social",
    es: "Social",
    cn: "社会",
    pt: "Social",
    tr: "Sosyal",
    ru: "Социальное",
    fr: "Social",
    de: "Sociale",
    pl: "Społeczny",
    ph: "Panlipunan",
  },
  privacy: {
    en: "Privacy",
    es: "Privacidad",
    cn: "隐私",
    pt: "Privacidade",
    tr: "Gizlilik",
    ru: "Конфиденциальность",
    fr: "Vie privée",
    de: "Privacy",
    pl: "Prywatność",
    ph: "Pagkapribado",
  },
  beasts: {
    en: "Beasts",
    es: "Bestias",
    cn: "野兽",
    pt: "Bestas",
    tr: "Canavarlar",
    ru: "Звери",
    fr: "Bêtes",
    de: "Beesten",
    pl: "Bestie",
    ph: "mga hayop",
  },
  warriors: {
    en: "Warriors",
    es: "Guerreros",
    cn: "勇士",
    pt: "Guerreiros",
    tr: "Savaşçılar",
    ru: "Воины",
    fr: "Guerriers",
    de: "Krijgers",
    pl: "Wojownicy",
    ph: "Mga mandirigma",
  },
  legions: {
    en: "Legions",
    es: "Legiones",
    cn: "军团",
    pt: "Legiões",
    tr: "Lejyonlar",
    ru: "Легионы",
    fr: "Légions",
    de: "Legioenen",
    pl: "Legiony",
    ph: "Lehiyon",
  },
  hunt: {
    en: "Hunt",
    es: "Cazar",
    cn: "打猎",
    pt: "Caçar",
    tr: "Avlanmak",
    ru: "Охота",
    fr: "Chasser",
    de: "Jagen",
    pl: "Polój",
    ph: "Manghuli",
  },
  usefulLinks: {
    en: "Useful Links",
    es: "Enlaces útiles",
    cn: "有用的链接",
    pt: "Links Úteis",
    tr: "İşe yarar bağlantılar",
    ru: "Полезные ссылки",
    fr: "Liens utiles",
    de: "Nuttige Links",
    pl: "Przydatne linki",
    ph: "Mga Kapaki-pakinabang na Link",
  },
  buyBlst: {
    en: "Buy $BLST",
    es: "Comprar $BLST",
    cn: "购买 $BLST",
    pt: "Compre $BLST",
    tr: "$BLST satın al",
    ru: "Купить $BLST",
    fr: "Acheter $BLST",
    de: "Koop $BLST",
    pl: "Kup $BLST",
    ph: "Bumili ng $BLST",
  },
  help: {
    en: "Help",
    es: "Ayuda",
    cn: "帮助",
    pt: "Ajuda",
    tr: "Yardım",
    ru: "Помощь",
    fr: "Aide",
    de: "Hulp",
    pl: "Pomoc",
    ph: "Tulong",
  },
  pancakeswap: {
    en: "Pancakeswap",
    es: "Pancakeswap",
    cn: "Pancakeswap",
    pt: "Pancakeswap",
    tr: "Pancakeswap",
    ru: "Pancakeswap",
    fr: "Pancakeswap",
    de: "Pancakeswap",
    pl: "Pancakeswap",
    ph: "Pancakeswap",
  },
  whitepaper: {
    en: "Whitepaper",
    es: "Libro blanco",
    cn: "白皮书",
    pt: "Whitepaper",
    tr: "Whitepaper",
    ru: "Белая бумага",
    fr: "Papier blanc",
    de: "Whitepaper",
    pl: "Biały papier",
    ph: "Puting papel",
  },
  twitter: {
    en: "Twitter",
    es: "Twitter",
    cn: "推特",
    pt: "Twitter",
    tr: "Twitter",
    ru: "Твиттер",
    fr: "Twitter",
    de: "Twitter",
    pl: "Twitter",
    ph: "Twitter",
  },
  telegram: {
    en: "Telegram",
    es: "Telegram",
    cn: "电报",
    pt: "Telegram",
    tr: "Telegram",
    ru: "Телеграмма",
    fr: "Télégramme",
    de: "Telegram",
    pl: "Telegram",
    ph: "Telegram",
  },
  discord: {
    en: "Discord",
    es: "Discord",
    cn: "Discord",
    pt: "Discord",
    tr: "Discord",
    ru: "Раздор",
    fr: "Discord",
    de: "Discord",
    pl: "Discord",
    ph: "Discord",
  },
  policy: {
    en: "Policy",
    es: "Política",
    cn: "政策",
    pt: "Políticas",
    tr: "Politika",
    ru: "Политика",
    fr: "Politique",
    de: "Beleid",
    pl: "Polityka",
    ph: "Patakaran",
  },
  madeWith: {
    en: "Made with",
    es: "Hecho con",
    cn: "用.....制作的",
    pt: "Feito com",
    tr: "tarafından yapılmıştır",
    ru: "Сделано с",
    fr: "Fait en",
    de: "Gemaakt met",
    pl: "Wykonane z",
    ph: "Ginawa gamit ang",
  },
  cryptoAgency: {
    en: "by Crypto Games Agency",
    es: "por Crypto Games Agency",
    cn: "由Crypto Games Agency",
    pt: "pela Crypto Games Agency",
    tr: "ile Crypto Games Agency",
    ru: "по Crypto Games Agency",
    fr: "par Crypto Games Agency",
    de: "door Crypto Games Agency",
    pl: "przez Crypto Games Agency",
    ph: "ng Crypto Games Agency",
  },
  createLegion: {
    en: "Create Legion",
    es: "Crear Legión",
    cn: "创造军团",
    pt: "Criar Legião",
    tr: "Lejyon Oluştur",
    ru: "Создать Легион",
    fr: "Créer une légion",
    de: "Creëer een Legioen ",
    pl: "Stwórz legion",
    ph: "Lumikha ng Lehiyon",
  },
  loadingBeasts: {
    en: "Loading Beasts...",
    es: "Cargando Bestias...",
    cn: "正在加载野兽...",
    pt: "Carregando Bestas ...",
    tr: "Canavarlar Yükleniyor ...",
    ru: "Загрузка зверей ...",
    fr: "Chargement des bêtes ...",
    de: "Beesten zijn aan het laden...",
    pl: "Ładowanie bestii ...",
    ph: "Naglo-load ng mga Hayop ...",
  },
  summonWarrior: {
    en: "Summon Warriors",
    es: "Invocar Guerreros",
    cn: "召唤战士",
    pt: "Invocar Guerreiro",
    tr: "Savaşçıları Çağır ...",
    ru: "Призвать воина",
    fr: "Invoquer un guerrier",
    de: "Koop krijgers",
    pl: "Przywołaj wojowników",
    ph: "Tawagin ang mandirigma",
  },
  currentWarriors: {
    en: "Current Warriors",
    es: "Guerreros Actuales",
    cn: "现在的勇士",
    pt: "Guerreiros Atuais",
    tr: "Mevcut Savaşçılar",
    ru: "Текущие воины",
    fr: "Guerriers actuels",
    de: "Huidige Krijgers",
    pl: "Obecni Wojownicy",
    ph: "Mga Kasalukuyang Mandirigma",
  },
  attackPower: {
    en: "Total Attack Power",
    es: "Poder de Ataque Total",
    cn: "总攻击力",
    pt: "Poder Total de Ataque",
    tr: "Toplam Saldırı Gücü",
    ru: "Общая сила атаки",
    fr: "Puissance d'attaque totale",
    de: "Totale aanvalskracht",
    pl: "Całkowita siła ataku",
    ph: "Kabuuang Lakas ng Pag-atake",
  },
  loadingWarriors: {
    en: "Loading Warriors ...",
    es: "Cargando Guerreros ...",
    cn: "加载勇士 ...",
    pt: "Carregando Guerreiros ...",
    tr: "Savaşçılar Yükleniyor ...",
    ru: "Загрузка воинов ...",
    fr: "Chargement guerriers ...",
    de: "Krijgers aan het laden…",
    pl: "Ładowanie wojowników ...",
    ph: "Naglo-load ng mga Mandirigma ...",
  },
  nameLegion: {
    en: "Name Your Legion",
    es: "Nombra tu legión",
    cn: "军团的名字",
    pt: "Nomeie sua Legião",
    tr: "Lejyonunuzu Adlandırın",
    ru: "Назовите свой легион",
    fr: "Nommez votre légion",
    de: "Naam voor je legioen",
    pl: "Nazwij swój legion",
    ph: "Pangalanan ang Iyong Lehiyon",
  },
  loadingTitle: {
    en: "Loading Warriors & Beasts...",
    es: "Cargando Guerreros y Bestias...",
    cn: "加载野兽和战士...",
    pt: "Carregando Guerreiros e Bestas ...",
    tr: "Canavarlar ve Savaşçılar Yükleniyor...",
    ru: "Загрузка зверей и воинов...",
    fr: "Charger des guerriers et des bêtes...",
    de: "Krijgers & beesten aan het laden...",
    pl: "Ładowanie wojowników i bestii...",
    ph: "load ng mga Mandirigma at Hayop...",
  },
  createLegionsBtn: {
    en: "Create legion with ",
    es: "Crear legión con ",
    cn: "创建军团 ",
    pt: "Crie legião com ",
    tr: "ile lejyon oluştur ",
    ru: "Создайте легион с ",
    fr: "Créez une légion avec ",
    de: "Creëer een legioen met ",
    pl: "Stwórz legion za pomocą ",
    ph: "Lumikha ng lehiyon gamit ang ",
  },
  btnBackToLegions: {
    en: "Back to your Legions",
    es: "Volver a sus Legiones",
    cn: "回到你的军团",
    pt: "De volta às suas Legiões",
    tr: "Lejyonlarınıza geri dönün",
    ru: "Назад к своим легионам",
    fr: "Retournez à vos légions",
    de: "Terug naar je legioenen",
    pl: "Powrót do twoich legionów",
    ph: "Bumalik sa iyong mga Lehiyon",
  },
  updateLegion: {
    en: "Update Legion",
    es: "Actualizar Legión",
    cn: "更新军团",
    pt: "Atualizar Legião",
    tr: "Lejyonu Güncelle",
    ru: "Обновить Легион",
    fr: "Mettre à jour Légion",
    de: "Legioen bijwerken",
    pl: "Aktualizuj Legion",
    ph: "I-update ang Legion",
  },
  yourOldLegionAP: {
    en: "Your existing legion has ",
    es: "Su legión existente tiene ",
    cn: "你现在的军团有 ",
    pt: "Sua legião existente tem ",
    tr: "Mevcut lejyonunuzda ",
    ru: "Ваш существующий легион имеет ",
    fr: "Votre légion actuelle a ",
    de: "Uw bestaande legioen heeft ",
    pl: "Twój istniejący legion ma ",
    ph: "Ang iyong kasalukuyang lehiyon ay mayroon",
  },
  availableWarrior: {
    en: "Available Warriors",
    es: "Guerreros disponibles",
    cn: "可用的勇士",
    pt: "Guerreiros Disponíveis",
    tr: "Mevcut Savaşçılar",
    ru: "Доступные воины",
    fr: "Guerriers disponibles",
    de: "Beschikbare Krijgers",
    pl: "Dostępni Wojownicy",
    ph: "Magagamit na mga Mandirigma",
  },
  availableBeast: {
    en: "Available Beasts",
    es: "Bestias disponibles",
    cn: "可用的野兽",
    pt: "Bestas Disponíveis",
    tr: "Mevcut Canavarlar",
    ru: "Доступные звери",
    fr: "Bêtes disponibles",
    de: "Beschikbare Beesten",
    pl: "Dostępne bestie",
    ph: "Magagamit na mga Hayop",
  },
  currentLegion: {
    en: "Current Legions",
    es: "Legiones actuales",
    cn: "当前军团",
    pt: "Legiões Atuais",
    tr: "Mevcut Lejyonlar",
    ru: "Текущие легионы",
    fr: "Légions actuelles",
    de: "Huidige Legioenen",
    pl: "Obecne Legiony",
    ph: "Kasalukuyang Lehiyon",
  },
  totalAp: {
    en: "Total AP",
    es: "AP Total",
    cn: "总 AP",
    pt: "PA total",
    tr: "Toplam AP",
    ru: "Всего AP",
    fr: "AP total",
    de: "Totale AP",
    pl: "Razem AP",
    ph: "Kabuuang AP",
  },
  top3Legions: {
    en: "Top 3 Legions",
    es: "Las 3 mejores legiones",
    cn: "前三名军团",
    pt: "Top 3 Legiões",
    tr: "En İyi 3 Lejyon",
    ru: "3 лучших легиона",
    fr: "Top 3 des légions",
    de: "Top 3 legioenen",
    pl: "3 Najlepsze legiony",
    ph: "Nangungunang 3 Lehiyon",
  },
  lowest: {
    en: "Lowest",
    es: "Más bajo",
    cn: "最低",
    pt: "Mais baixo",
    tr: "En düşük",
    ru: "Самый низкий",
    fr: "Plus bas",
    de: "Laagste",
    pl: "Najniższy",
    ph: "Pinakamababa",
  },
  highest: {
    en: "Highest",
    es: "Más alto",
    cn: "最高",
    pt: "Mais alto",
    tr: "En yüksek",
    ru: "Наибольший",
    fr: "Plus haut",
    de: "Hoogste",
    pl: "Najwyższy",
    ph: "Pinakamataas",
  },
  sortByAp: {
    en: "Sort By AP",
    es: "Ordenar por AP",
    cn: "按 AP 排序",
    pt: "Classificar por AP",
    tr: "AP'ye göre sırala",
    ru: "Сортировать по AP",
    fr: "Trier par AP",
    de: "Sorteren op AP",
    pl: "Sortuj według AP",
    ph: "Pagbukud-bukurin Ayon sa AP",
  },
  filterByAp: {
    en: "Filter By AP",
    es: "Filtrar por AP",
    cn: "按 AP 过滤",
    pt: "Filtrar por AP",
    tr: "AP'ye göre filtrele",
    ru: "Фильтровать по AP",
    fr: "Filtrer par AP",
    de: "Filteren op AP",
    pl: "Filtruj według AP",
    ph: "Salain Ayon sa AP",
  },
  huntStatus: {
    en: "Hunt Status",
    es: "Estado de Caza",
    cn: "狩猎状态",
    pt: "Status de Caça",
    tr: "Av Durumu",
    ru: "Статус охоты",
    fr: "Statut de chasse",
    de: "Jaagstatus",
    pl: "Status polowania",
    ph: "Katayuan ng Hunt",
  },
  green: {
    en: "Green",
    es: "Verde",
    cn: "绿色",
    pt: "Verde",
    tr: "Yeşil",
    ru: "Зеленый",
    fr: "Vert",
    de: "Groen",
    pl: "Zielony",
    ph: "Berde",
  },
  orange: {
    en: "Orange",
    es: "Naranja",
    cn: "橘色",
    pt: "Laranja",
    tr: "Turuncu",
    ru: "апельсин",
    fr: "Orange",
    de: "Oranje",
    pl: "Pomarańczowy",
    ph: "Kahel",
  },
  red: {
    en: "Red",
    es: "Rojo",
    cn: "红色",
    pt: "Vermelho",
    tr: "Kırmızı",
    ru: "красный",
    fr: "Rouge",
    de: "Rood",
    pl: "Czerwony",
    ph: "Pula",
  },
  hideWeakLegions: {
    en: "Hide Weak Legions",
    es: "Ocultar Legiones Débiles",
    cn: "隐藏弱小的军团",
    pt: "Esconder Legiões Fracas",
    tr: "Zayıf Lejyonları Gizle",
    ru: "Скрыть слабые легионы",
    fr: "Cachez les légions faibles",
    de: "Verberg zwakke legioenen",
    pl: "Ukryj słabe legiony",
    ph: "Itago ang mga Mahinang Lehiyon",
  },
  buySupply: {
    en: "Buy Supplies",
    es: "Comprar Más Suministros",
    cn: "购买更多用品",
    pt: "Comprar Suprimentos",
    tr: "Daha Fazla Malzeme Satın Alın",
    ru: "Купите больше расходных материалов",
    fr: "Acheter fournitures",
    de: "Koop meer benodigdheden",
    pl: "Kup więcej materiałów",
    ph: "Bumili ng kagamitan",
  },
  filterLevel: {
    en: "Filter By Level",
    es: "Filtrar por Nivel",
    cn: "按级别过滤",
    pt: "Filtrar por Nível",
    tr: "Seviyeye Göre Filtrele",
    ru: "Фильтровать по уровню",
    fr: "Filtrer par niveau",
    de: "Filteren op niveau",
    pl: "Filtruj według poziomu",
    ph: "Salain Ayon sa Antas",
  },
  loadingMonsters: {
    en: "Loading Monsters...",
    es: "Cargando Monstruos...",
    cn: "加载怪物...",
    pt: "Carregando Monstros...",
    tr: "Canavarlar Yükleniyor...",
    ru: "Загрузка монстров...",
    fr: "Chargement des monstres...",
    de: "Monsters aan het laden...",
    pl: "Ładowanie potworów...",
    ph: "Naglo-load ng mga Halimaw...",
  },
  yourInventory: {
    en: "YOUR INVENTORY",
    es: "SU INVENTARIO",
    cn: "您的库存",
    pt: "SEU INVENTÁRIO",
    tr: "ENVANTERİNİZ",
    ru: "ВАШ ИНВЕНТАРЬ",
    fr: "Votre inventaire",
    de: "UW INVENTARIS",
    pl: "TWÓJ EKWIPUNEK",
    ph: "IYONG IMBENTARYO",
  },
  availableLegions: {
    en: "Available legions to hunt",
    es: "Legiones disponibles para cazar",
    cn: "可用军团狩猎",
    pt: "Legiões disponíveis para caçar",
    tr: "Avlanmak için mevcut lejyonlar",
    ru: "Доступные легионы для охоты",
    fr: "Légions disponibles pour chasser",
    de: "Beschikbare legioenen om te jagen",
    pl: "Dostępne legiony do polowania",
    ph: "Magagamit na mga legion upang manghuli",
  },
  waitingTimeToHunt: {
    en: "Waiting time until next hunt",
    es: "Tiempo de espera hasta la próxima cacería",
    cn: "等待下一次狩猎的时间",
    pt: "Tempo de espera até a próxima caçada",
    tr: "Bir sonraki av için bekleme süresi",
    ru: "Время ожидания до следующей охоты",
    fr: "Temps d'attente jusqu'à la prochaine chasse",
    de: "Wachttijd tot de volgende jacht",
    pl: "Czas oczekiwania do następnego polowania",
    ph: "Oras ng paghihintay hanggang sa susunod na panghuhuli",
  },
  yourMaxAp: {
    en: "AP of top legion",
    es: "AP de la legión superior",
    cn: "顶级军团AP",
    pt: "AP da sua melhor legião",
    tr: "Baş lejyonun AP'si",
    ru: "AP высшего легиона",
    fr: "AP de la légion supérieure",
    de: "AP van top legioen",
    pl: "AP najwyższego legionu",
    ph: "AP ng nangungunang legion",
  },
  unClaimed: {
    en: "Unclaimed $BLST",
    es: "$BLST No Reclamado",
    cn: "没领取的 $BLST",
    pt: "$BLST Não Reivindicado",
    tr: "Talep edilmemiş $BLST",
    ru: "Невостребованные $BLST",
    fr: "$BLST non réclamé",
    de: "Niet-geclaimde $BLST",
    pl: "Nieodebrane $BLST",
    ph: "Hindi nakuha na $BLST",
  },
  claimTax: {
    en: "If you'd claim now, you'd pay",
    es: "Si reclamaras ahora, pagarías",
    cn: "如果您现在领取，您将支付",
    pt: "Se você reivindicar agora, você pagaria",
    tr: "Şimdi almayı talep ederseniz vergi ödeyeceksiniz.",
    ru: "Если бы вы требовали сейчас, вы бы заплатили",
    fr: "Si vous réclamiez maintenant, vous paieriez",
    de: "Als je nu zou claimen, zou je betalen",
    pl: "Jeśli odbierzesz teraz, zapłacisz",
    ph: "Kung mag-claim ka ngayon, magbabayad ka",
  },
  claimTaxVal: {
    en: "$BLST tax",
    es: "impuesto $BLST",
    cn: "$BLST 税",
    pt: "Taxa de $BLST",
    tr: "$BLST vergisi",
    ru: "$BLST налог",
    fr: "Taxe $BLST",
    de: "$BLST belasting",
    pl: "$BLST podatek",
    ph: "buwis sa $BLST",
  },
  taxDaysLeft: {
    en: "Tax Days Left",
    es: "Días de Impuestos Restantes",
    cn: "剩余纳税天数",
    pt: "Dias de Taxas Restantes",
    tr: "Kalan Vergi Günü",
    ru: "Осталось налоговых дней",
    fr: "Jours d'impôt restants",
    de: "Resterende belastingdagen",
    pl: "Pozostałe dni podatkowe",
    ph: "Araw ng tax na natitira",
  },
  BLSTInYourWallet: {
    en: "$BLST in Your Wallet",
    es: "$BLST en su Billetera",
    cn: "钱包中的 $BLST",
    pt: "$BLST em sua Carteira",
    tr: "Cüzdanınızda $BLST",
    ru: "$BLST в вашем кошельке",
    fr: "$BLST dans votre portefeuille",
    de: "$BLST in uw portemonnee",
    pl: "$BLST w Twoim portfelu",
    ph: "$BLST sa Iyong Wallet",
  },
  takeAction: {
    en: "TAKE ACTION",
    es: "Tomar Acción",
    cn: "行动",
    pt: "Tome uma Ação",
    tr: "Harekete Geç",
    ru: "Действовать",
    fr: "Passer à l'action",
    de: "Actie ondernemen",
    pl: "Podejmij działanie",
    ph: "Gumawa ng aksyon",
  },
  takeActionSummonBeastQuantity: {
    en: "SUMMON BEASTS QUANTITY",
    es: "Invocar cantidad de bestias",
    cn: "召唤兽数量",
    pt: "QUANTIDADE DE BESTAS INVOCADAS",
    tr: "Çağrılan Canavar Miktarı",
    ru: "Призыв зверя Количество",
    fr: "Quantité d'invocation de bête",
    de: "Hoeveelheid aan te kopen beesten",
    pl: "Ilość Przyzwania Bestii",
    ph: "Ipatawag ang Dami ng Hayop",
  },
  takeActionSummonWarriorQuantity: {
    en: "SUMMON WARRIORS QUANTITY",
    es: "Invocar cantidad de guerreros",
    cn: "召唤勇士数量",
    pt: "QUANTIDADE DE GUERREIROS INVOCADOS",
    tr: "Çağrılan Savaşçı Miktarı",
    ru: "Призыв Воина Количество",
    fr: "Quantité d'invocation de guerrier",
    de: "Hoeveelheid aan te kopen krijgers",
    pl: "Ilość przywołania wojownika",
    ph: "Ipatawag ang Dami ng Mandirigma",
  },
  takeActionCreateLegion: {
    en: "CREATE LEGION",
    es: "Crear Legion",
    cn: "购买野兽",
    pt: "CRIAR LEGIÃO",
    tr: "Canavar Satın Al",
    ru: "создать легион",
    fr: "Créer légion",
    de: "Legioen creëren",
    pl: "Stwórz legion",
    ph: "Bumili ng mga Hayop",
  },
  takeActionMassHunt: {
    en: "Mass Hunt",
    es: "Caza masiva",
    cn: "大规模狩猎",
    pt: "Caça em Massa",
    tr: "Toplu Av",
    ru: "Массовая охота",
    fr: "Chasse en masse",
    de: "Massaal Jagen",
    pl: "Masowe polowanie",
    ph: "Mass Hunt",
  },
  takeActionBuyBeasts: {
    en: "Beasts Market",
    es: "Mercado de bestias",
    cn: "野兽市场",
    pt: "Mercado de Feras",
    tr: "Canavar Marketi",
    ru: "Рынок зверей",
    fr: "Marché aux bêtes",
    de: "Beestenmarkt",
    pl: "Rynek Bestii",
    ph: "Pamilihan ng mga hayop",
  },
  takeActionBuyWarriors: {
    en: "Warriors Market",
    es: "Mercado de guerreros",
    cn: "勇士市场",
    pt: "Mercado de guerreiros",
    tr: "Savaşçı Marketi",
    ru: "Рынок воинов",
    fr: "Marché des guerriers",
    de: "Krijgersmarkt",
    pl: "Rynek wojowników",
    ph: "Pamilihan ng mga mandirigma",
  },
  takeActionBuyLegions: {
    en: "Legions Market",
    es: "Mercado de Legiones",
    cn: "军团市场",
    pt: "Mercado de Legiões",
    tr: "Lejyon Marketi",
    ru: "Рынок легионов",
    fr: "Marché des' légions",
    de: "Legioenenmarkt",
    pl: "Rynek Legionów",
    ph: "Pamilihan ng mga Lehiyon",
  },
  takeActionDextools: {
    en: "Dextools Chart",
    es: "Gráfico de Dextools",
    cn: "Dextools 图表",
    pt: "Gráfico de Dextools",
    tr: "Dextools Tablosu",
    ru: "графика Dextools",
    fr: "Graphique Dextool",
    de: "Dextools grafiek",
    pl: "Wykres Dextools",
    ph: "Chart ng Dextools",
  },
  takeActionBuyBlst: {
    en: "BUY $BLST",
    es: "COMPRAR $BLST",
    cn: "购买$BLST",
    pt: "COMPRE $BLST",
    tr: "$BLST SATIN AL",
    ru: "КУПИТЬ $BLST",
    fr: "Acheter $BLST",
    de: "KOOP $BLST",
    pl: "KUP $BLST",
    ph: "BUMILI ng $BLST",
  },
  yourAchievements: {
    en: "YOUR ACHIEVEMENTS",
    es: "Sus Logros",
    cn: "你的成就",
    pt: "Suas Conquistas",
    tr: "Başarımlarınız",
    ru: "Ваши достижения",
    fr: "Vos réalisations",
    de: "Jouw prestaties",
    pl: "Twoje osiągnięcia",
    ph: "Ang iyong mga nagawa",
  },
  readInstructionsInWhitePaper: {
    en: "READ INSTRUCTIONS IN WHITEPAPER",
    es: "Lea las instrucciones en el documento técnico",
    cn: "阅读白皮书中的说明",
    pt: "LEIA AS INSTRUÇÕES NO WHITEPAPER",
    tr: "Whitepaper Talimatlarını Okuyunuz",
    ru: "Прочтите инструкции в Техническом документе",
    fr: "Lire les instructions dans le livre blanc",
    de: "Lees de instructies in de whitepaper",
    pl: "Przeczytaj instrukcje w whitepaper",
    ph: "Basahin ang Mga Tagubilin sa Whitepaper",
  },
  summonWarriorSuccessful: {
    en: "Warriors summoned successfully! To see your warriors, please click here.",
    es: "¡Guerreros convocados con éxito! Para ver tus guerreros, por favor, haz clic aquí",
    cn: "成功召唤勇士！如果你看到你所有的战士，请点击这里！",
    pt: "Guerreiros convocados com sucesso! Para ver os seus guerreiros, clique aqui!",
    tr: "Savaşçılarını başarıyla çağırdın! Tüm savaşçılarınızı görüntülemek için lütfen buna tıklayınız!",
    ru: "Призыв воинов успешно! Если вы видите всех своих воинов, нажмите здесь!",
    fr: "Invoquez des guerriers avec succès ! Si vous voyez tous vos guerriers, veuillez cliquer ici !",
    de: "Je krijgers zijn aangekocht! Klik hier om al je krijgers te zien.",
    pl: "Przyzywanie wojowników pomyślne! Jeśli chcesz zobaczyć wszystkich swoich wojowników, kliknij tu!",
    ph: "Matagumpay na ipatawag ang mga Mandirigma! Kung nakikita mo ang iyong lahat ng mga mandirigma, mangyaring pindutin ito!",
  },
  summonBeastSuccessful: {
    en: "Beasts summoned successfully! To see your warriors, please click here.",
    es: "¡Bestias convocadas con éxito! Para ver a sus bestias, por favor haga clic aquí!",
    cn: "召唤兽成功！如果你看到你所有的野兽，请点击这里！",
    pt: "Bestas convocadas com sucesso! Para ver suas bestas, por favor clique aqui!",
    tr: "Canavarlarını başarıyla çağırdın! Tüm canavarlarınızı görüntülemek için lütfen buraya tıklayınız!",
    ru: "Призыв Зверей успешно! Если вы видите всех своих зверей, пожалуйста, нажмите здесь!",
    fr: "Invoquez des bêtes avec succès ! Si vous voyez toutes vos bêtes, veuillez cliquer ici!",
    de: "Je beesten zijn aangekocht! Klik hier om al je beesten te zien.",
    pl: "Przyzywanie bestii pomyślne! Jeśli chcesz zobaczyć wszystkie swoje bestie, kliknij tu!",
    ph: "Matagumpay na ipatawag ang mga Hayop! Kung nakikita mo ang lahat ng iyong mga hayop, mangyaring pindutin ito!",
  },
  summoningBeasts: {
    en: "Summoning Beasts...",
    es: "Invocando Bestias...",
    cn: "召唤兽中...",
    pt: "Invocando Bestas...",
    tr: "Çağrılan Canavarlar...",
    ru: "Призыв зверей...",
    fr: "Invoquer des bêtes...",
    de: "Beesten aan het kopen...",
    pl: "Przyzywanie Bestii...",
    ph: "Pagtawag ng mga Hayop...",
  },
  nadodoWatching: {
    en: "NADODO IS WATCHING",
    es: "Nadodo está mirando",
    cn: "纳多多在看",
    pt: "Nadodo ESTÁ ASSISTINDO",
    tr: "Nadodo izliyor",
    ru: "Nadodo наблюдает",
    fr: "Nadodo est regarde",
    de: "Nadodo kijkt",
    pl: "Nadodo patrzy",
    ph: "Nanunuod si Nadodo",
  },
  summoningWarriors: {
    en: "Summoning Warriors...",
    es: "Invocando Guerreros...",
    cn: "召唤战士...",
    pt: "Invocando Guerreiros...",
    tr: "Savaşçıları Çağırmak...",
    ru: "Призыв воинов...",
    fr: "Invoquer des guerriers...",
    de: "Krijgers aan het kopen...",
    pl: "Przyzywanie wojowników...",
    ph: "Pagtawag ng mga Mandirigma...",
  },
  marketplaceTax: {
    en: "Marketplace Tax",
    es: "Impuesto del Mercado",
    cn: "市场税",
    pt: "Taxa de mercado",
    tr: "Pazar Vergisi",
    ru: "Торговый налог",
    fr: "Taxe de marché",
    de: "Marktbelasting",
    pl: "Podatek od rynku",
    ph: "Buwis sa pamilihan",
  },
  huntTax: {
    en: "Hunt Tax",
    es: "Impuesto de caza",
    cn: "狩猎税",
    pt: "Taxa de caça",
    tr: "Av vergisi",
    ru: "Охотничий налог",
    fr: "Taxe de chasse",
    de: "Jachtbelasting",
    pl: "Podatek od polowania",
    ph: "Buwis sa panghuhuli",
  },
  buyTax: {
    en: "Buy Tax",
    es: "Impuesto de Compra",
    cn: "购买税",
    pt: "Taxa de Compra",
    tr: "Satın Alma Vergisi",
    ru: "Купить налог",
    fr: "Taxe d'achat",
    de: "Aankoopbelasting",
    pl: "Podatek od kupna",
    ph: "Bumili ng Buwis",
  },
  sellTax: {
    en: "Sell Tax",
    es: "Impuesto de Venta",
    cn: "出销售税",
    pt: "Taxa de Venda",
    tr: "Satış Vergisi",
    ru: "Налог на продажу",
    fr: "Taxe de vente",
    de: "Verkoopbelasting",
    pl: "Podatek od Sprzedaży",
    ph: "Magbenta ng Buwis",
  },
  legionDamagePerHunt: {
    en: "Legion Damage Per Hunt",
    es: "Daño de la legión por caza",
    cn: "每次狩猎的军团伤害",
    pt: "Dano da Legião por Caçada",
    tr: "Av Başına Lejyon Hasarı",
    ru: "Урон Легиона за охоту",
    fr: "Dégâts de légion par chasse",
    de: "Legioenschade per jacht",
    pl: "Obrażenia legionu na polowanie",
    ph: "Legion Damage Bawat Hunt",
  },
  summoningFee: {
    en: "Summoning Fee",
    es: "Cuota de Invocación",
    cn: "召唤费",
    pt: "Taxa de Invocação",
    tr: "Çağırma ücreti",
    ru: "плата за вызов",
    fr: "Coût d'invocation",
    de: "Belasting op aankoop ",
    pl: "Opłata za przywołanie",
    ph: "Summoning Fee",
  },
  SuppliesFee14Hunts: {
    en: "Supplies Fee for 14 Hunts",
    es: "Tarifa de suministros para 14 cacerías",
    cn: "14 次狩猎的用品费",
    pt: "Taxa de suprimentos para 14 Caçadas",
    tr: "14 Av için Malzeme Ücreti",
    ru: "Плата за припасы за 14 охот",
    fr: "Frais de fournitures pour 14 chasses",
    de: "Tarief voor 14 jachtpartijen",
    pl: "Opłata za zapasy za 14 polowań",
    ph: "Bayad sa kagamitan para sa 14 na Hunt",
  },
  SuppliesFee28Hunts: {
    en: "Supplies Fee for 28 Hunts",
    es: "Tarifa de suministros para 28 cacerías",
    cn: "28 次狩猎的用品费",
    pt: "Taxa de Suprimentos para 28 Caçadas",
    tr: "28 Av için Malzeme Ücreti",
    ru: "Плата за припасы за 28 охот",
    fr: "Frais de fournitures pour 28 chasses",
    de: "Tarief voor 28 jachtpartijen",
    pl: "Opłata za zapasy za 28 polowań",
    ph: "Bayad sa kagamitan para sa 28 na Hunt",
  },
  RewardPool: {
    en: "Reward Pool",
    es: "Fondo de Recompensas",
    cn: "奖励池",
    pt: "Fundo de Recompensas",
    tr: "Ödül Havuzu",
    ru: "Пул вознаграждений",
    fr: "Pool de récompenses",
    de: "Beloningspool",
    pl: "Pula nagród",
    ph: "Pool ng Gantimpala",
  },
  ReservePool: {
    en: "Reserve Pool",
    es: "Fondo de Reserva",
    cn: "储备池",
    pt: "Fundo Reserva",
    tr: "Rezerv Havuzu",
    ru: "Резервный бассейн",
    fr: "Piscine de réserve",
    de: "Reserve fonds",
    pl: "Rezerwuj pulę",
    ph: "Reserve Pool",
  },
  LiquidityPool: {
    en: "Liquidity Pool",
    es: "Fondo de Liquidez",
    cn: "流动资金池",
    pt: "Fundo de Liquidez",
    tr: "Likidite Havuzu",
    ru: "Пул ликвидности",
    fr: "Pool de liquidités",
    de: "Liquiditeitsfonds",
    pl: "Pula płynności",
    ph: "Liquidity Pool",
  },
  buyingSupplies: {
    en: "Buying Supplies...",
    es: "Compra de Suministros...",
    cn: "购买用品...",
    pt: "Compra de Suprimentos...",
    tr: "Malzeme Satın Alma...",
    ru: "Покупка расходных материалов...",
    fr: "Acheter des fournitures...",
    de: "Benodigdheden kopen...",
    pl: "Kupowanie materiałów eksploatacyjnych...",
    ph: "Pagbili ng kagamitan...",
  },
  loadingLegions: {
    en: "Loading Legions...",
    es: "Cargando Legiones...",
    cn: "装载军团...",
    pt: "Carregando Legiões...",
    tr: "Lejyonları Yükleme...",
    ru: "Загрузка легионов...",
    fr: "Chargement des légions...",
    de: "Legioenen aan het laden...",
    pl: "Ładowanie legionów...",
    ph: "Naglo-load ng Lehiyon...",
  },
  suppliesNeeded: {
    en: "Supplies needed",
    es: "Se necesitan suministros",
    cn: "需要用品",
    pt: "Suprimentos são necessários",
    tr: "Malzemeler gerekli",
    ru: "Необходимы расходные материалы",
    fr: "Des fournitures sont nécessaires",
    de: "Benodigdheden zijn nodig",
    pl: "Potrzebne są materiały eksploatacyjne",
    ph: "Mga kailangan na kagamitan",
  },
  noMintedLegion: {
    en: "You need to create a legion to start hunting!",
    es: "¡Necesitas crear una legión primero para comenzar a cazar!",
    cn: "您需要先创建一个军团才能开始狩猎！",
    pt: "Você precisa criar uma legião primeiro para começar a caçar!",
    tr: "Avlanmaya başlamak için önce bir lejyon oluşturmanız gerekiyor!",
    ru: "Вам нужно сначала создать легион, чтобы начать охоту!",
    fr: "Vous devez d'abord créer une légion pour commencer à chasser !",
    de: "Je moet eerst een legioen creëren om te kunnen jagen!",
    pl: "Aby rozpocząć polowanie, musisz najpierw stworzyć legion!",
    ph: "Kailangan mo munang lumikha ng isang lehiyon upang simulan ang panghuhuli!",
  },
  marketplace: {
    en: "Marketplace",
    es: "Mercado",
    cn: "市场",
    pt: "Mercado",
    tr: "Marketplace",
    ru: "Торговая площадка",
    fr: "Marché",
    de: "Markt",
    pl: "Rynek",
    ph: "Pamilihan",
  },
  sortBy: {
    en: "Sort By",
    es: "Ordenar por",
    cn: "排序方式",
    pt: "Ordenar por",
    tr: "Göre sırala",
    ru: "Сортировать по",
    fr: "Trier par",
    de: "Sorteer op",
    pl: "Sortuj według",
    ph: "Pagbukud-bukurin Ayon",
  },
  confirm: {
    en: "Confirm",
    es: "Confirmar",
    cn: "确认",
    pt: "Confirmar",
    tr: "Onayla",
    ru: "Подтверждать",
    fr: "Confirmer",
    de: "Bevestigen",
    pl: "Potwierdzać",
    ph: "Kumpirmahin",
  },
  huntTime: {
    en: "Hunting Time!",
    es: "Tiempo de caza!",
    cn: "狩猎时间！",
    pt: "Hora da Caça!",
    tr: "Av Zamanı!",
    ru: "Время охоты!",
    fr: "Temps de chasse !",
    de: "Tijd om te jagen!",
    pl: "Czas polowania!",
    ph: "Oras ng Panghuhuli!",
  },
  huntTimeSubtitle1: {
    en: "Your legion is now attacking the monster:",
    es: "Tu legión ahora está atacando al monstruo:",
    cn: "你的军团现在正在攻击怪物：",
    pt: "Sua legião está agora atacando o monstro:",
    tr: "Lejyonunuz şimdi canavara saldırıyor:",
    ru: "Теперь ваш легион атакует монстра:",
    fr: "Votre légion maintenant attaque le monstre :",
    de: "Je legioen valt nu het monster aan:",
    pl: "Twój legion atakuje teraz potwora:",
    ph: "Inaatake na ngayon ng iyong lehiyon ang halimaw:",
  },
  congratulation: {
    en: "Congratulations!",
    es: "Felicidades!",
    cn: "恭喜！",
    pt: "Parabéns!",
    tr: "Tebrikler!",
    ru: "Поздравляем!",
    fr: "Félicitations!",
    de: "Gefeliciteerd!",
    pl: "Gratulacje!",
    ph: "Binabati kita!",
  },
  congSubtitle1: {
    en: "You defeated this monster!",
    es: "Has derrotado a este monstruo!",
    cn: "你打败了这个怪物！",
    pt: "Você derrotou este monstro!",
    tr: "Bu canavarı yendin!",
    ru: "Вы победили этого монстра!",
    fr: "Vous avez vaincu ce monstre !",
    de: "Je hebt dit monster verslagen!",
    pl: "Pokonałeś tego potwora!",
    ph: "Natalo mo ang halimaw na ito!",
  },
  congSubtitle3: {
    en: "To win you need to roll equal or less than:",
    es: "Para ganar necesitas tirar igual o menos que:",
    cn: "要获胜，您需要滚动等于或小于：",
    pt: "Para ganhar você precisa rolar igual ou menor que:",
    tr: "Kazanmak için aşağıdakilere eşit veya daha az atış yapmanız gerekir:",
    ru: "Чтобы выиграть, вам нужно выбросить меньше или равно:",
    fr: "Pour gagner, vous devez obtenir un résultat égal ou inférieur à :",
    de: "Om te winnen moet je gelijk of minder gooien dan:",
    pl: "Aby wygrać, musisz wyrzucić równą lub mniejszą niż:",
    ph: "Upang manalo kailangan mong gumulong katumbas o mas mababa sa:",
  },
  continue: {
    en: "Continue",
    es: "Continuar",
    cn: "继续",
    pt: "Continuar",
    tr: "Devam et",
    ru: "Продолжать",
    fr: "Continuez",
    de: "Doorgaan",
    pl: "Kontyntynuj",
    ph: "Magpatuloy",
  },
  defeatTitle: {
    en: "Better luck next time...",
    es: "Mejor suerte la próxima vez...",
    cn: "下次好运...",
    pt: "Mais sorte da próxima vez...",
    tr: "Bir Dahaki Sefere İyi Şanslar...",
    ru: "Повезет в следующий раз...",
    fr: "Plus de chance la prochaine fois...",
    de: "Volgende keer beter...",
    pl: "Następnym razem będziesz miał więcej szczęścia...",
    ph: "Baka palarin sa susunod...",
  },
  defeatSubtitle1: {
    en: "Your legion did not succeed in getting Bloodstone from this monster.",
    es: "Tu legión no logró obtener Bloodstone de este monstruo hoy.",
    cn: "你的军团今天没能从这个怪物那里得到bloodstone. N",
    pt: "Sua legião não conseguiu pegar Bloodstone deste monstro.",
    tr: "Lejyonunuz bugün bu canavardan Kantaşı almayı başaramadı.",
    ru: "Сегодня вашему легиону не удалось получить Кровавый камень от этого монстра.",
    fr: "Votre légion n'a pas réussi à obtenir Bloodstone de ce monstre aujourd'hui.",
    de: "Je legioen is er niet in geslaagd om Bloodstone van dit monster te winning.",
    pl: "Twojemu legionowi nie udało się zdobyć Bloodstone tego potwora.",
    ph: "Ang iyong lehiyon ay hindi nagtagumpay sa pagkuha ng Bloodstone mula sa halimaw na ito ngayon.",
  },
  defeatSubtitle2: {
    en: "To win you need to roll equal or less than:",
    es: "Para ganar necesitas tirar igual o menos que:",
    cn: "要获胜，您需要滚动等于或小于：",
    pt: "Para ganhar você precisa rolar igual ou menor que:",
    tr: "Kazanmak için aşağıdakilere eşit veya daha az atış yapmanız gerekir:",
    ru: "Чтобы выиграть, вам нужно выбросить меньше или равно:",
    fr: "Pour gagner, vous devez obtenir un résultat égal ou inférieur à :",
    de: "Om te winnen moet je gelijk of minder gooien dan:",
    pl: "Aby wygrać, musisz wyrzucić równą lub mniejszą niż:",
    ph: "Upang manalo kailangan mong gumulong katumbas o mas mababa sa:",
  },
  yourRollTitle: {
    en: "Your roll is",
    es: "Tu tirada es de",
    cn: "你的卷是",
    pt: "Seu roll é",
    tr: "Atış Miktarın",
    ru: "Ваш рулон",
    fr: "Votre rouleau est",
    de: "Je hebt gegooid",
    pl: "Twoja rzut to",
    ph: "Ang iyong rolyo ay",
  },
  showMyWarrior: {
    en: "Show Only My Warriors",
    es: "Mostrar solo mis guerreros",
    cn: "只显示我的勇士",
    pt: "Mostrar apenas meus guerreiros",
    tr: "Yalnızca Savaşçılarımı Göster",
    ru: "Показать только моих воинов",
    fr: "Afficher uniquement mes guerriers",
    de: "Toon alleen mijn krijgers",
    pl: "Pokaż tylko moich wojowników",
    ph: "Ipakita Lamang ang Aking Mga Mandirigma",
  },
  pleaseWait: {
    en: "Please wait...",
    es: "Espere por favor...",
    cn: "请稍等...",
    pt: "Por favor, aguarde...",
    tr: "Lütfen bekleyiniz...",
    ru: "Пожалуйста, подождите...",
    fr: "S'il vous plaît, attendez...",
    de: "Wacht alsjeblieft...",
    pl: "Proszę czekać...",
    ph: "Mangyaring Maghintay...",
  },
  first: {
    en: "First",
    es: "Primero",
    cn: "第一的",
    pt: "Primeiro",
    tr: "Öncelikle",
    ru: "Первый",
    fr: "Première",
    de: "Eerste",
    pl: "Pierwszy",
    ph: "Una",
  },
  last: {
    en: "Last",
    es: "Último",
    cn: "最后的",
    pt: "Último",
    tr: "Son",
    ru: "Прошлой",
    fr: "Dernier",
    de: "Laatste",
    pl: "Ostatni",
    ph: "Huli",
  },
  previous: {
    en: "Previous",
    es: "Anterior",
    cn: "以前的",
    pt: "Anterior",
    tr: "Önceki",
    ru: "Предыдущий",
    fr: "Précédent",
    de: "Vorige",
    pl: "Poprzedni",
    ph: "Nakaraang",
  },
  next: {
    en: "Next",
    es: "Próximo",
    cn: "下一个",
    pt: "Próximo",
    tr: "Sonraki",
    ru: "Следующий",
    fr: "Suivant",
    de: "Volgende",
    pl: "Następny",
    ph: "Susunod",
  },
  showMyBeast: {
    en: "Show Only My Beasts",
    es: "Mostrar Solo Mis Bestias",
    cn: "只显示我的野兽",
    pt: "Mostrar apenas minhas feras",
    tr: "Sadece Canavarlarımı Göster",
    ru: "Показывать только моих зверей",
    fr: "Afficher uniquement mes bêtes",
    de: "Toon alleen mijn beesten",
    pl: "Pokaż tylko moje bestie",
    ph: "Ipakita ang Aking Mga Hayop Lamang",
  },
  showMyLegion: {
    en: "Show Only My Legions",
    es: "Mostrar Solo Mis Legiones",
    cn: "仅显示我的军团",
    pt: "Mostrar apenas Minhas Legiões",
    tr: "Yalnızca Lejyonlarımı Göster",
    ru: "Показать только мои легионы",
    fr: "Afficher uniquement mes légions",
    de: "Toon alleen mijn legioenen",
    pl: "Pokaż tylko moje legiony",
    ph: "Ipakita ang Aking Mga Lehiyon Lamang",
  },
  filterByHunts: {
    en: "Filter By Hunts Left",
    es: "Filtrar por Cazas restantes",
    cn: "按左侧狩猎过滤",
    pt: "Filtrar por Caças restantes",
    tr: "Soldaki Avlara Göre Filtrele",
    ru: "Фильтровать по оставшимся охотам",
    fr: "Filtrer par chasses restantes",
    de: "Filter volgens resterende jachten",
    pl: "Filtruj według dostępnych polowań",
    ph: "I-filter Ayon sa Hunts Kaliwa",
  },
  listOnMarketplace: {
    en: "List On Marketplace",
    es: "Listar en el Mercado",
    cn: "列表到市场",
    pt: "Listar no mercado",
    tr: "Markette Listele",
    ru: "Список на рынок",
    fr: "Liste sur le marché",
    de: "Verkoop op de markt",
    pl: "Dodaj na rynek",
    ph: "Listahan Sa Pamilihan",
  },
  congSubtitle2: {
    en: "You have been rewarded",
    es: "Has sido recompensado",
    cn: "你得到了回报",
    pt: "Você foi recompensado",
    tr: "Ödüllendirildin",
    ru: "Вы были вознаграждены",
    fr: "Vous avez été récompensé",
    de: "Je bent beloond",
    pl: "Zostałeś nagrodzony",
    ph: "Ikaw ay ginantimpalaan",
  },
  warriorMaster: {
    en: "Warrior Master",
    es: "Maestro Guerrero",
    cn: "战士大师",
    pt: "Mestre Guerreiro",
    tr: "Savaşçı Usta",
    ru: "Мастер воинов",
    fr: "Maître guerrier",
    de: "Krijger Meester",
    pl: "Mistrz Wojowników",
    ph: "Maestro ng mandirigma",
  },
  beastMaster: {
    en: "Beast Master",
    es: "Maestro de Bestias",
    cn: "野兽大师",
    pt: "Mestre das Bestas",
    tr: "Canavar Ustası",
    ru: "Повелитель зверей",
    fr: "Maître des bêtes",
    de: "Beest Meester",
    pl: "Meester Bestii",
    ph: "Master ng mga Hayop",
  },
  legionMaster: {
    en: "Legion Master",
    es: "Maestro de la Legión",
    cn: "军团长",
    pt: "Mestre da Legião",
    tr: "Lejyon Ustası",
    ru: "Мастер легиона",
    fr: "Maître de la Légion",
    de: "Legioen Meester",
    pl: "Mistrz Legionów",
    ph: "Master ng mga Lehiyon",
  },
  monsterConqueror: {
    en: "Monster Conqueror",
    es: "Conquistador de Monstruos",
    cn: "怪物征服者",
    pt: "Conquistador de Monstros",
    tr: "Canavar Fatihi",
    ru: "Завоеватель монстров",
    fr: "Conquérant de monstre",
    de: "Monster Veroveraar",
    pl: "Zdobywca Potworów",
    ph: "Mananakop ng halimaw",
  },
  "King/Queen": {
    en: "King/Queen of Nicah",
    es: "Rey/Reina de Nicah",
    cn: "国王/王后尼卡",
    pt: "Rei/Rainha de Nicah",
    tr: "Kral/Kraliçe Nicah",
    ru: "Король/Королева Ника",
    fr: "Roi/Reine Nicah",
    de: "Koning/Koningin van Nicah",
    pl: "Król/Królowa Nicah",
    ph: "Hari/Reyna Nicah",
  },
  warriorMasterEx: {
    en: "Own a level 6 warrior",
    es: "Ten un Guerrero de nivel 6",
    cn: "拥有一名6级战士",
    pt: "Possuir um guerreiro de nível 6",
    tr: "6. seviye bir savaşçıya sahip ol",
    ru: "Иметь воина 6 уровня",
    fr: "Posséder un guerrier de niveau 6",
    de: "Bezit een krijger van niveau 6",
    pl: "Posiadaj wojownika na poziomie 6",
    ph: "Pagmamay-ari ng level 6 na mandirigma",
  },
  beastMasterEx: {
    en: "Own a beast with 20 capacity",
    es: "Posee una Bestia con 20 de capacidad.",
    cn: "拥有一只20容量的野兽",
    pt: "Possuir uma fera com capacidade de 20",
    tr: "20 kapasiteli bir canavara sahip olun",
    ru: "Собственный зверь с 20 вместимостью",
    fr: "Posséder une bête avec une capacité de 20",
    de: "Bezit een beest met een capaciteit van 20",
    pl: "Posiadaj bestię o pojemności 20",
    ph: "Pagmamay-ari ng isang hayop na may 20 kapasidad",
  },
  legionMasterEx: {
    en: "Own 10 legions of 30,000+ AP",
    es: "Posee 10 Legiones de 30,000+ AP",
    cn: "拥有10个军团30,000+ AP",
    pt: "Possui 10 legiões de 30.000+ AP",
    tr: "30.000'den fazla AP'ye sahip 10 lejyona sahip olun",
    ru: "Иметь 10 легионов по 30 000+ AP",
    fr: "Posséder 10 légions de 30 000+ AP",
    de: "Bezit 10 legioenen van meer dan 30 000 AP",
    pl: "Posiadaj 10 legionów po 30 000+ AP",
    ph: "Pagmamay-ari ng 10 lehiyon ng 30,000+ AP",
  },
  monsterConquerorEx: {
    en: "Win a hunt of Monster 23",
    es: "Gana una cacería al Monstruo 23",
    cn: "赢得一场怪物 23 的追捕",
    pt: "Vença uma caçada ao Monstro 23",
    tr: "Canavar 23 avını kazan",
    ru: "Выиграйте охоту на монстра 23",
    fr: "Gagnez une chasse au monstre 23",
    de: "Versla monster 23",
    pl: "Wygraj polowanie na Potwora 23",
    ph: "Manalo ng isang panghuhuli ng Monster 23",
  },
  "King/QueenEx": {
    en: "Win a hunt of Monster 24",
    es: "Gana una cacería al Monstruo 24",
    cn: "赢得一场怪物 24 的追捕",
    pt: "Vença uma caçada ao Monstro 24",
    tr: "Canavar 24 avını kazan",
    ru: "Выиграйте охоту на монстра 24",
    fr: "Gagnez une chasse au monstre 24",
    de: "Versla monster 24",
    pl: "Wygraj polowanie na Potwora 24",
    ph: "Manalo ng isang panghuhuli ng Monster 24",
  },
  sell: {
    en: "Sell",
    es: "Vender",
    cn: "卖",
    pt: "Vender",
    tr: "Sat",
    ru: "Продавать",
    fr: "Vendre",
    de: "Verkoop",
    pl: "Sprzedaj",
    ph: "Ibenta",
  },
  noBeastFilter: {
    en: "No beasts with this capacity. Summon some more!",
    es: "No hay bestias con esta capacidad. ¡Invoca a algunos más!",
    cn: "没有这种能力的野兽。再召唤一些！",
    pt: "Nenhuma besta com essa capacidade. Convoque mais algumas!",
    tr: "Bu kapasitede canavar yok. Biraz daha çağır!",
    ru: "Нет зверей с такой способностью. Позовите еще!",
    fr: "Aucune bête avec cette capacité. Invoquez-en d'autres !",
    de: "Geen beesten met deze capaciteit. Koop er meer!",
    pl: "Żadnych bestii z taką zdolnością. Przywołaj więcej!",
    ph: "Walang mga hayop na may ganitong kapasidad. Magpatawag pa!",
  },
  noWarriorFilter: {
    en: "No warriors with this level/AP. Summon some more!",
    es: "No hay guerreros con este nivel/AP. ¡Invoca a algunos más!",
    cn: "没有这个级别/AP的战士。再召唤一些！",
    pt: "Nenhum guerreiro com este nível/AP. Convoque mais alguns!",
    tr: "Bu Level/AP'ye sahip bir savaşçı yok. Biraz daha çağır!",
    ru: "Нет воинов с этим уровнем/AP. Позовите еще!",
    fr: "Aucun guerrier avec ce niveau/AP. Invoquez-en d'autres !",
    de: "Geen krijgers met dit niveau/AP. Koop er meer!",
    pl: "Żadnych wojowników z tym poziomem/AP. Przywołaj więcej!",
    ph: "Walang mga mandirigma na may ganitong antas/AP. Magpatawag pa!",
  },
  LongFeeToolTip: {
    en: "Fee to create your legion is ",
    es: "La tarifa para crear tu legión es",
    cn: "创造军团的费用是",
    pt: "A taxa para criar sua legião é",
    tr: "Lejyonunuzu oluşturma ücreti",
    ru: "Плата за создание своего легиона составляет",
    fr: "Les frais pour créer votre légion sont",
    de: "De kosten om je legioen te creëren is",
    pl: "Opłata za utworzenie legionu wynosi",
    ph: "Ang bayad sa paggawa ng iyong lehiyon ay",
  },
  ShortFeeToolTip: {
    en: "Fee",
    es: "Tarifa",
    cn: "费用",
    pt: "Taxa",
    tr: "Ücret",
    ru: "тариф",
    fr: "Frais",
    de: "Tarief",
    pl: "Opłata",
    ph: "Bayad",
  },
  feeToUpdate: {
    en: "Fee to update ",
    es: "Tarifa para actualizar ",
    cn: "更新费用 ",
    pt: "Taxa para atualizar ",
    tr: "Güncelleme ücreti ",
    ru: "Плата за обновление ",
    fr: "Frais de mise à jour ",
    de: "Kosten om te updaten ",
    pl: "Opłata za aktualizację ",
    ph: "Bayad sa pag-update ",
  },
  to: {
    en: "to",
    es: "para",
    cn: "到",
    pt: "para",
    tr: "ile",
    ru: "для",
    fr: "Pour",
    de: "voor",
    pl: "do",
    ph: "sa",
  },
  create: {
    en: "Create",
    es: "Crear",
    cn: "创造",
    pt: "Criar",
    tr: "Yaratmak",
    ru: "Создавать",
    fr: "Créer",
    de: "Creëren",
    pl: "Tworzyć",
    ph: "Lumikha",
  },
  notEnoughBeasts: {
    en: "Not enough beasts",
    es: "No hay suficientes bestias",
    cn: "野兽不够",
    pt: "Não há bestas suficientes",
    tr: "Yeterli canavar yok",
    ru: "Недостаточно зверей",
    fr: "Pas assez de bêtes",
    de: "Er zijn niet genoeg beesten",
    pl: "Za mało bestii",
    ph: "Hindi sapat ang mga hayop",
  },
  min: {
    en: "min",
    es: "min",
    cn: "最少需要",
    pt: "min",
    tr: "dk",
    ru: "мин",
    fr: "Min",
    de: "min",
    pl: "min",
    ph: "min",
  },
  needed: {
    en: "needed",
    es: "necesario",
    cn: "",
    pt: "necessário",
    tr: "gerekli",
    ru: "требуется",
    fr: "nécessaire",
    de: "nodig",
    pl: "potrzebne",
    ph: "kailangan",
  },
  existingAPIs: {
    en: "Existing AP is",
    es: "El AP existente es",
    cn: "现有 AP 是",
    pt: "O AP existente é",
    tr: "Mevcut AP",
    ru: "Существующая ПА является",
    fr: "Le AP existant est",
    de: "Bestaande AP is",
    pl: "Istniejący AP to",
    ph: "Ang kasalukuyang API",
  },
  update: {
    en: "Update",
    es: "Actualizar",
    cn: "更新",
    pt: "Atualizar",
    tr: "Güncelleme",
    ru: "Обновлять",
    fr: "Mettre à jour",
    de: "Bijwerken",
    pl: "Aktualizacja",
    ph: "Update",
  },
  base: {
    en: "Base",
    es: "Base",
    cn: "根据",
    pt: "Base",
    tr: "Üs",
    ru: "база",
    fr: "Base",
    de: "Basis",
    pl: "Baza",
    ph: "Base",
  },
  bonus: {
    en: "Bonus",
    es: "Bono",
    cn: "奖金",
    pt: "Bônus",
    tr: "Bonus",
    ru: "Бонус",
    fr: "Prime",
    de: "Bonus",
    pl: "Bonus",
    ph: "Bonus",
  },
  toWin: {
    en: "to Win",
    es: "para ganar",
    cn: "赢",
    pt: "para Ganhar",
    tr: "kazanmak",
    ru: "побеждать",
    fr: "pour gagner",
    de: "om te winnen",
    pl: "aby wygrać",
    ph: "para manalo",
  },
  updatePrice: {
    en: "Update Price",
    es: "Actualizar Precio",
    cn: "更新价格",
    pt: "Atualizar preço",
    tr: "Fiyatı Güncelle",
    ru: "цена обновления",
    fr: "Mettre à jour le prix",
    de: "Prijs bijwerken",
    pl: "Zaktualizuj cenę",
    ph: "I-update ang Presyo",
  },
  huntTransactionFailed: {
    en: "Transaction failed, please try again!",
    es: "La transacción ha fallado, ¡inténtalo de nuevo!",
    cn: "交易失败，请重试！",
    pt: "A transação falhou, tente novamente!",
    tr: "İşlem başarısız, lütfen tekrar deneyin!",
    ru: "Транзакция не удалась, попробуйте еще раз!",
    fr: "La transaction a échoué, veuillez réessayer !",
    de: "Transactie is mislukt, probeer het opnieuw!",
    pl: "Transakcja nie powiodła się, spróbuj ponownie!",
    ph: "Nabigo ang transaksyon, pakisubukang muli!",
  },
  maxSellPrice: {
    en: "The price must be lower than 5,000,000.",
    es: "El precio debe ser inferior a 5,000,000.",
    cn: "价格必须小于 5,000,000。",
    pt: "O preço deve ser inferior a 5,000,000.",
    tr: "Fiyat 5,000,000'dan az olmalıdır.",
    ru: "Цена должна быть меньше 5,000,000.",
    fr: "Le prix doit être inférieur à 5,000,000.",
    de: "De prijs moet lager zijn dan 5.000.000.",
    pl: "Cena musi być mniejsza niż 5,000,000.",
    ph: "Ang presyo ay dapat na mas mababa sa 5,000,000.",
  },
  healthy: {
    en: "Healthy",
    es: "Saludable",
    cn: "健康",
    pt: "Saudável",
    tr: "Sağlıklı",
    ru: "Здоровый",
    fr: "Sain",
    de: "Gezond",
    pl: "Zdrowy",
    ph: "Malusog",
  },
  waitLoading: {
    en: "Wait a moment, loading...",
    es: "Espera un momento, cargando...",
    cn: "稍等，加载中...",
    pt: "Aguarde um momento, carregando...",
    tr: "Bekleyiniz, yükleniyor...",
    ru: "Подождите, идет загрузка...",
    fr: "Attendez un instant, chargement...",
    de: "Wacht even, aan het laden...",
    pl: "Poczekaj chwilę, ładowanie...",
    ph: "Sandali, naglo-load...",
  },
  priceIn: {
    en: "Price In",
    es: "Precio en",
    cn: "价格在",
    pt: "Preço em",
    tr: "Fiyat",
    ru: "Цена в",
    fr: "Prix en",
    de: "Prijs in",
    pl: "Cena w",
    ph: "Presyo Sa",
  },
  filterBy: {
    en: "Filter By",
    es: "Filtrar por",
    cn: "过滤",
    pt: "Filtrar por",
    tr: "Tarafından filtrelendi",
    ru: "Фильтровать по",
    fr: "Filtrer par",
    de: "Filteren op",
    pl: "Filtruj według",
    ph: "I-filter Ayon sa",
  },
  hunts: {
    en: "Hunts",
    es: "Cacerías",
    cn: "狩猎",
    pt: "Caças",
    tr: "Avlar",
    ru: "Охоты",
    fr: "Chasses",
    de: "Jachtpartijen",
    pl: "Polowania",
    ph: "Hunts",
  },
  hSymbol: {
    en: "H",
    es: "C",
    cn: "S",
    pt: "C",
    tr: "A",
    ru: "O",
    fr: "C",
    de: "J",
    pl: "P",
    ph: "H",
  },
  noToClaim: {
    en: "There is no $BLST to claim.",
    es: "No hay $BLST para reclamar.",
    cn: "没有可领取的 $BLST.",
    pt: "Não há $BLST para reivindicar.",
    tr: "Talep edilebilecek $BLST yok.",
    ru: "Нет $BLST, на которые можно претендовать.",
    fr: "Il n'y a pas de $BLST à réclamer.",
    de: "Er is geen $BLST om te claimen.",
    pl: "Nie ma $BLST do odebrania.",
    ph: "Walang $BLST na i-claim.",
  },
  huntMonsters: {
    en: "Please hunt monsters to get $BLST.",
    es: "Por favor, caza monstruos para obtener $BLST.",
    cn: "请狩猎怪物以获得$BLST.",
    pt: "Por favor, cace monstros para obter $BLST.",
    tr: "$BLST almak için lütfen canavarları avlayın.",
    ru: "Пожалуйста, охотьтесь на монстров, чтобы получить $BLST.",
    fr: "Veuillez chasser des monstres pour obtenir $BLST.",
    de: "Jaag op monsters om $BLST te winnen.",
    pl: "Proszę polować na potwory, aby wygrać $BLST.",
    ph: "Manghuli ng mga halimaw para makakuha ng $BLST.",
  },
  aboutToClaim: {
    en: "You are about to claim",
    es: "Estás a punto de reclamar",
    cn: "您即将领取",
    pt: "Você está prestes a reivindicar",
    tr: "Talep etmek üzeresiniz",
    ru: "Вы собираетесь требовать",
    fr: "Vous êtes sur le point de réclamer",
    de: "Je staat op het punt om te claimen",
    pl: "Masz zamiar odebrać",
    ph: "Malapit ka nang mag-claim",
  },
  taxFree: {
    en: "tax-free",
    es: "libre de impuestos",
    cn: "免税",
    pt: "livre de taxas",
    tr: "vergisiz",
    ru: "не облагаемый налогом",
    fr: "exempt d'impôt",
    de: "belastingvrij",
    pl: "wolne od podatku",
    ph: "walang buwis",
  },
  willReceive: {
    en: "You will receive",
    es: "Usted recibirá",
    cn: "您将收到",
    pt: "Você receberá",
    tr: "alacaksın",
    ru: "Вы получите",
    fr: "Vous allez recevoir",
    de: "Je ontvangt",
    pl: "Otrzymasz",
    ph: "Matatanggap mo",
  },
  inYourWallet: {
    en: "in your wallet",
    es: "en tu billetera",
    cn: "在你的钱包里",
    pt: "na sua carteira",
    tr: "cüzdanında",
    ru: "в твоем кошельке",
    fr: "Dans votre portefeuille",
    de: "in je portemonnee",
    pl: "w twoim portfelu",
    ph: "sa wallet mo",
  },
  goAhead: {
    en: "Do you want to go ahead?",
    es: "¿Quieres seguir adelante?",
    cn: "你想继续吗？",
    pt: "Você quer ir em frente?",
    tr: "Devam etmek istiyor musun?",
    ru: "Вы хотите идти вперед?",
    fr: "Voulez-vous aller de l'avant?",
    de: "Wil je verder?",
    pl: "Czy chcesz iść dalej?",
    ph: "Gusto mo bang ituloy?",
  },
  with: {
    en: "with",
    es: "con",
    cn: "和",
    pt: "com",
    tr: "ile birlikte",
    ru: "с",
    fr: "Avec",
    de: "met",
    pl: "z",
    ph: "kasama",
  },
  tax: {
    en: "tax",
    es: "impuesto",
    cn: "税",
    pt: "taxa",
    tr: "vergi",
    ru: "налог",
    fr: "Impôt",
    de: "belasting",
    pl: "podatek",
    ph: "buwis",
  },
  willPay: {
    en: "You will pay",
    es: "Tu vas a pagar",
    cn: "你会付出代价的",
    pt: "Você pagará",
    tr: "Ödeyeceksin",
    ru: "Вы будете платить",
    fr: "Tu paieras",
    de: "Je zal betaalen",
    pl: "Zapłacisz",
    ph: "Magbabayad ka",
  },
  receiveOnly: {
    en: "and receive only",
    es: "y recibir solo",
    cn: "并且只接收",
    pt: "e receba apenas",
    tr: "Sadece alış",
    ru: "и получать только",
    fr: "et recevez uniquement",
    de: "en ontvang alleen",
    pl: "i tylko otrzymasz",
    ph: "at tumanggap lamang",
  },
  youWait: {
    en: "If you wait",
    es: "Si esperas",
    cn: "如果你等",
    pt: "Se você esperar",
    tr: "Eğer beklersen",
    ru: "Если вы подождете",
    fr: "Si tu attends",
    de: "Als je wacht",
    pl: "Jeśli poczekasz",
    ph: "Kung maghihintay ka",
  },
  willToClaim: {
    en: "days, then you will be able to claim tax-free.",
    es: "días, entonces podrá reclamar libre de impuestos.",
    cn: "天，然后你就可以免税.",
    pt: "dias, então você poderá reivindicar com isenção de taxas.",
    tr: "günler, o zaman vergiden muaf olmayı talep edebileceksiniz.",
    ru: "дней, тогда вы можете претендовать на освобождение от налогов.",
    fr: "Jours, ensuite vous pouvez prétendre libre impôt.",
    de: "dagen, dan kan je belastingvrij claimen.",
    pl: "dni, wtedy będziesz mógł ubiegać się o zwolnienie z podatku.",
    ph: "araw, pagkatapos ay makakapag-claim ka nang walang buwis.",
  },
  sureGoAhead: {
    en: "Are you sure you want to go ahead now?",
    es: "¿Estás seguro de que quieres continuar ahora?",
    cn: "你确定现在要继续吗？",
    pt: "Tem certeza de que quer ir em frente agora?",
    tr: "Şimdi devam etmek istediğinden emin misin?",
    ru: "Вы уверены, что хотите продолжить?",
    fr: "Êtes-vous sûr de vouloir continuer maintenant ?",
    de: "Weet je zeker dat je nu verder wilt?",
    pl: "Czy na pewno chcesz teraz kontynuować?",
    ph: "Sigurado ka bang gusto mong magpatuloy ngayon?",
  },
  cancel: {
    en: "Cancel",
    es: "Cancelar",
    cn: "取消",
    pt: "Cancelar",
    tr: "İptal Et",
    ru: "Отмена",
    fr: "Annuler",
    de: "Annuleren",
    pl: "Anulować",
    ph: "Kanselahin",
  },
  claimTaxFree: {
    en: "Claim tax-free",
    es: "Reclamar libre de impuestos",
    cn: "申请免税",
    pt: "Reivindicar isenção de taxas",
    tr: "Vergiden muaf olmayı talep",
    ru: "Заявление об освобождении от уплаты налогов",
    fr: "Prétendre libre impôt",
    de: "Belastingvrij claimen",
    pl: "Roszczenie wolne od podatku",
    ph: "Mag-claim na walang buwis",
  },
  claimPayTax: {
    en: "Claim and pay tax",
    es: "Reclamar y pagar impuestos",
    cn: "索赔并缴纳税款",
    pt: "Receber e pagar a taxa",
    tr: "Vergi talep et ve öde",
    ru: "Требовать и платить налог",
    fr: "Réclamer et payer l'impôt",
    de: "Belasting claimen en betalen",
    pl: "Odbierz i zapłać podatek",
    ph: "Mag-claim at magbayad ng buwis",
  },
  helpText: {
    en: "Need help from our team? Send us a messages with the form below, and we’ll get back to you within 24 hours if your request relates to a bug/issue in the game.",
    es: "¿Necesita ayuda de nuestro equipo? Envíenos un mensaje con el siguiente formulario y nos pondremos en contacto con usted dentro de las 24 horas si su solicitud se relaciona con un error/problema en el juego.",
    cn: "需要我们的帮助吗？使用以下表格向我们发送消息，如果您的请求涉及游戏中的错误/问题，我们将在 24 小时内回复您.",
    pt: "Precisa de ajuda da nossa equipe? Envie-nos uma mensagem com o formulário abaixo e entraremos em contato com você dentro de 24 horas se sua solicitação estiver relacionada a um bug/problema no jogo.",
    tr: "Desteğe mi ihtiyacınız var? Aşağıdaki formu kullanarak bize bir mesaj gönderin, eğer sorununuz oyundaki bir hata/sorunla ilgiliyse 24 saat içerisinde size geri dönüş sağlayacağız.",
    ru: "Нужна помощь от нашей команды? Отправьте нам сообщение с формой ниже, и мы свяжемся с вами в течение 24 часов, если ваш запрос связан с ошибкой/проблемой в игре.",
    fr: "Besoin d'aide de notre équipe? Envoyez-nous un message avec le formulaire ci-dessous, et nous vous répondrons dans les 24 heures si votre demande concerne un bug/problème dans le jeu.",
    de: "Hulp nodig van ons team? Stuur ons een bericht met het onderstaande formulier en we nemen binnen 24 uur contact met je op als je verzoek betrekking heeft op een bug/probleem in het spel.",
    pl: "Potrzebujesz pomocy naszego zespołu? Wyślij nam wiadomość za pomocą poniższego formularza, a skontaktujemy się z Tobą w ciągu 24 godzin, jeśli Twoja prośba dotyczy błędu/problemu w grze.",
    ph: "Kailangan mo ng tulong mula sa aming team? Magpadala sa amin ng mga mensahe kasama ang form sa ibaba, at babalikan ka namin sa loob ng 24 na oras kung ang iyong kahilingan ay nauugnay sa isang bug/isyu sa laro.",
  },
  email: {
    en: "Email",
    es: "Correo electrónico",
    cn: "电子邮件",
    pt: "E-mail",
    tr: "E-posta",
    ru: "Эл. адрес",
    fr: "E-mail",
    de: "E-mail",
    pl: "E-mail",
    ph: "Email",
  },
  yourEmail: {
    en: "Your Email",
    es: "Tu correo electrónico",
    cn: "你的邮件",
    pt: "Seu email",
    tr: "E-posta adresiniz",
    ru: "Ваш адрес электронной почты",
    fr: "Votre e-mail",
    de: "Jouw email",
    pl: "Twój email",
    ph: "Ang email mo",
  },
  discordId: {
    en: "Discord name",
    es: "ID de Discord",
    cn: "DiscordID",
    pt: "ID do Discord",
    tr: "Discord Kullanıcı Adı",
    ru: "DiscordID",
    fr: "DiscordID",
    de: "DiscordID",
    pl: "DiscordID",
    ph: "DiscordID",
  },
  yourDiscord: {
    en: "Your Discord name (optional)",
    es: "Tu Nombre de Discord (opcional)",
    cn: "你的discord（可选）",
    pt: "Seu Discord (opcional)",
    tr: "Discord Kullanı Adınız (isteğe bağlı)",
    ru: "Ваш дискорд (необязательно)",
    fr: "Votre Discord (optionnel)",
    de: "Uw Discord (optioneel)",
    pl: "Twój Discord (opcjonalnie)",
    ph: "Iyong Discord (opsyonal)",
  },
  title: {
    en: "Title",
    es: "Título",
    cn: "标题",
    pt: "Título",
    tr: "Başlık",
    ru: "Заголовок",
    fr: "Titre",
    de: "Titel",
    pl: "Tytuł",
    ph: "Pamagat",
  },
  titleIssue: {
    en: "Title of your issue",
    es: "Título de su problema",
    cn: "您问题的标题",
    pt: "Título do seu problema",
    tr: "Sorununuzun başlığı",
    ru: "Название вашего вопроса",
    fr: "Titre de votre problème",
    de: "Titel van je probleem",
    pl: "Tytuł twojego problemu",
    ph: "Pamagat ng iyong isyu",
  },
  descriptionText: {
    en: "Please describe your issue with as many details as possible.",
    es: "Describa su problema con tantos detalles como sea posible.",
    cn: "请尽可能详细地描述您的问题.",
    pt: "Descreva seu problema com o máximo de detalhes possível.",
    tr: "Lütfen sorununuzu mümkün olduğunca fazla ayrıntıyla açıklayın.",
    ru: "Пожалуйста, опишите вашу проблему как можно подробнее.",
    fr: "Veuillez décrire votre problème avec autant de détails que possible.",
    de: "Beschrijf uw probleem met zoveel mogelijk details.",
    pl: "Opisz swój problem, podając jak najwięcej szczegółów.",
    ph: "Pakilarawan hangga’t maari ang iyong isyu sa pinakamaraming detalye.",
  },
  priority: {
    en: "Priority",
    es: "Prioridad",
    cn: "优先",
    pt: "Prioridade",
    tr: "Öncelik",
    ru: "приоритет",
    fr: "Priorité",
    de: "Prioriteit",
    pl: "Priorytet",
    ph: "Priyoridad",
  },
  selectPriority: {
    en: "Please select priority",
    es: "Por favor seleccione prioridad",
    cn: "请选择优先级",
    pt: "Selecione a prioridade",
    tr: "Lütfen önceliği seçin",
    ru: "Выберите приоритет",
    fr: "Veuillez sélectionner la priorité",
    de: "Selecteer de prioriteit",
    pl: "Wybierz priorytet",
    ph: "Mangyaring pumili ng priyoridad",
  },
  low: {
    en: "Low",
    es: "Bajo",
    cn: "低的",
    pt: "Baixo",
    tr: "Düşük",
    ru: "Низкий",
    fr: "Sous",
    de: "Laag",
    pl: "Niski",
    ph: "Mababa",
  },
  medium: {
    en: "Medium",
    es: "Medio",
    cn: "中等的",
    pt: "Médio",
    tr: "Orta",
    ru: "Середина",
    fr: "Médium",
    de: "Medium",
    pl: "Średni",
    ph: "Katamtaman",
  },
  high: {
    en: "High",
    es: "Elevado",
    cn: "高的",
    pt: "Alto",
    tr: "Yüksek",
    ru: "Высоко",
    fr: "Haut",
    de: "Hoog",
    pl: "Wysoka",
    ph: "Mataas",
  },
  urgent: {
    en: "Urgent",
    es: "Urgente",
    cn: "紧急",
    pt: "Urgente",
    tr: "Acil",
    ru: "Срочный",
    fr: "Urgent",
    de: "Dringend",
    pl: "Pilne",
    ph: "Madalian",
  },
  createTicket: {
    en: "Create Ticket",
    es: "Crear un ticket",
    cn: "创建工单",
    pt: "Criar ticket",
    tr: "Bilet Oluştur",
    ru: "Создать тикет",
    fr: "Créer un billet",
    de: "Ticket aanmaken",
    pl: "Utwórz bilet",
    ph: "Lumikha ng Ticket",
  },
  description: {
    en: "Description",
    es: "Descripción",
    cn: "描述",
    pt: "Descrição",
    tr: "Tanım",
    ru: "Описание",
    fr: "Description",
    de: "Omschrijving",
    pl: "Opis",
    ph: "Paglalarawan",
  },
  attachmentFile: {
    en: "Attachment File (optional)",
    es: "Archivo adjunto (opcional)",
    cn: "附件文件（可选)",
    pt: "Arquivo de anexo (opcional)",
    tr: "Ek Dosyası (isteğe bağlı)",
    ru: "Вложенный файл (необязательно)",
    fr: "Fichier joint (optionnel)",
    de: "Bijlage bestand (optioneel)",
    pl: "Plik załącznika (opcjonalnie)",
    ph: "Attachment File (opsyonal)",
  },
  back: {
    en: "Back",
    es: "Atrás",
    cn: "后退",
    pt: "Voltar",
    tr: "Geri",
    ru: "Назад",
    fr: "Dos",
    de: "Terug",
    pl: "Wstecz",
    ph: "Bumalik",
  },
  supplyCostLoading: {
    en: "Loading Supplies Fee",
    es: "Costo de suministro de carga",
    cn: "加载供应成本",
    pt: "Carregando Custo de Taxas",
    tr: "Yükleme Tedarik Maliyeti",
    ru: "Стоимость поставки груза",
    fr: "Chargement du coût d'approvisionnement",
    de: "Kosten van benodigdheden aan het laden",
    pl: "Ładowanie kosztów dostaw",
    ph: "Naglo-load ang Gastos ng Supply",
  },
  wallet: {
    en: "Use my wallet",
    es: "Usar mi billetera",
    cn: "钱包",
    pt: "Usar minha carteira",
    tr: "Cüzdanımı Kullan",
    ru: "Бумажник",
    fr: "Utiliser mon portefeuille",
    de: "Gebruik portemonnee",
    pl: "Użyj portfel",
    ph: "Gamitin ang aking wallet",
  },
  unclaimed: {
    en: "Use unclaimed",
    es: "Usar no reclamado",
    cn: "没领取的",
    pt: "Usar não reclamado",
    tr: "Talep edilmemiş olanı kullan",
    ru: "Невостребованный",
    fr: "Utiliser non revendiquée",
    de: "Gebruik niet-geclaimed",
    pl: "Użyj nieodebrane",
    ph: "Gamitin ang mga hindi nakuha",
  },
  massHuntResult: {
    en: "Mass Hunt Result",
    es: "Resultado de la cacería masiva",
    cn: "大规模狩猎结果",
    pt: "Resultado da caçada em massa",
    tr: "Toplu Av Sonucu",
    ru: "Результат массовой охоты",
    fr: "Résultat de la chasse de masse",
    de: "Resultaat massajacht",
    pl: "Wynik masowego polowania",
    ph: "Resulta ng Mass Hunt",
  },
  maxRoll: {
    en: "Max roll to win",
    es: "Rollo máximo para ganar",
    cn: "最大滚动获胜",
    pt: "Rolagem máxima para ganhar",
    tr: "Kazanmak için maksimum rulo",
    ru: "Максимальный бросок, чтобы выиграть",
    fr: "Lancer max pour gagner",
    de: "Max rol om te winnen",
    pl: "Maksymalna liczba rzutów, aby wygrać",
    ph: "Max roll para manalo",
  },
  yourRoll: {
    en: "Your roll",
    es: "tu rollo",
    cn: "你的卷",
    pt: "Seu rolo",
    tr: "senin rulon",
    ru: "Ваш рулон",
    fr: "Votre rouleau",
    de: "Jouw rol",
    pl: "Twoja rolka",
    ph: "Iyong rolyo",
  },
  won: {
    en: "WON",
    es: "GANADO",
    cn: "韩元",
    pt: "VENCEU",
    tr: "KAZANDI",
    ru: "ПОБЕДИЛ",
    fr: "GAGNÉ",
    de: "WON",
    pl: "WYGRAŁA",
    ph: "NANALO",
  },
  lost: {
    en: "LOST",
    es: "PERDIÓ",
    cn: "丢失",
    pt: "PERDIDO",
    tr: "KAYIP",
    ru: "ПОТЕРЯННЫЙ",
    fr: "PERDU",
    de: "VERLOREN",
    pl: "STRACONY",
    ph: "NAWALA",
  },
  noLegionToHunt: {
    en: "No legion available to hunt.",
    es: "No hay legión disponible para cazar.",
    cn: "没有军团可供狩猎。",
    pt: "Nenhuma legião disponível para caçar.",
    tr: "Avlanacak lejyon yok.",
    ru: "Нет легиона, доступного для охоты.",
    fr: "Aucune légion disponible pour chasser.",
    de: "Geen legioen beschikbaar om op te jagen.",
    pl: "Brak legionu do polowania.",
    ph: "Walang legion na magagamit upang manghuli.",
  },
  monster: {
    en: "Monster",
    es: "Monstruo",
    cn: "怪物",
    pt: "Monstro",
    tr: "Canavar",
    ru: "Монстр",
    fr: "Monstre",
    de: "Monster",
    pl: "Potwór",
    ph: "Halimaw",
  },
  addBUSD: {
    en: "Add more BUSD to your wallet to hunt.",
    es: "Agregue más BUSD a su billetera para cazar.",
    cn: "将更多 BUSD 添加到您的钱包中以进行狩猎。",
    pt: "Adicione mais BUSD à sua carteira para caçar.",
    tr: "Avlanmak için cüzdanınıza daha fazla BUSD ekleyin.",
    ru: "Добавьте больше BUSD в свой кошелек, чтобы охотиться.",
    fr: "Ajoutez plus de BUSD à votre portefeuille pour chasser.",
    de: "Voeg meer BUSD toe aan uw portemonnee om te jagen.",
    pl: "Dodaj więcej BUSD do swojego portfela, aby polować.",
    ph: "Magdagdag ng higit pang BUSD sa iyong wallet upang manghuli.",
  },
  payMarketplaceTax: {
    en: "If you sold, you will pay marketplace tax.",
    es: "Si vendió, pagará el impuesto de mercado.",
    cn: "如果您出售，您将支付市场税。",
    pt: "Se você vendeu, pagará imposto de mercado.",
    tr: "Sattıysanız, pazar vergisi ödersiniz.",
    ru: "Если вы продали, вы будете платить рыночный налог.",
    fr: "Si vous avez vendu, vous paierez la taxe de marché.",
    de: "Als je verkocht, betaal je marktplaatsbelasting.",
    pl: "Jeśli sprzedałeś, zapłacisz podatek od rynku.",
    ph: "Kung nagbebenta ka, magbabayad ka ng buwis sa pamilihan.",
  },
  massExecute: {
    en: "Mass Execute",
    es: "ejecución masiva",
    cn: "批量执行",
    pt: "Execução em massa",
    tr: "Toplu Yürütme",
    ru: "Массовая казнь",
    fr: "Exécuter en masse",
    de: "massa-executie",
    pl: "Masowe wykonanie",
    ph: "Isagawa ang Misa",
  },
  name: {
    en: "Name",
    es: "nombre",
    cn: "姓名",
    pt: "nome",
    tr: "isim",
    ru: "название",
    fr: "Nom",
    de: "naam",
    pl: "nazwać",
    ph: "pangalan",
  },
  approvalAllBeastsAndWarriors: {
    en: "Please approve access to your Warriors and Beasts...",
    es: "Aprueba el acceso a tus Warriors and Beasts...",
    cn: "请批准访问您的勇士和野兽...",
    pt: "Por favor, aprove o acesso aos seus guerreiros e feras...",
    tr: "Lütfen Savaşçılarınıza ve Canavarlarınıza erişimi onaylayın...",
    ru: "Пожалуйста, подтвердите доступ к вашим воинам и зверям...",
    fr: "Veuillez approuver l'accès à vos Guerriers et Bêtes...",
    de: "Keur de toegang tot je Warriors and Beasts goed...",
    pl: "Zatwierdź dostęp do swoich Wojowników i Bestii...",
    ph: "Mangyaring aprubahan ang pag-access sa iyong mga Mandirigma at Hayop...",
  },
  approvalAllBeasts: {
    en: "Please approve access to your Beasts...",
    es: "Aprueba el acceso a tus Bestias...",
    cn: "请批准访问您的野兽...",
    pt: "Por favor, aprove o acesso às suas Bestas...",
    tr: "Lütfen Canavarlarınıza erişimi onaylayın...",
    ru: "Пожалуйста, разрешите доступ к вашим Зверям...",
    fr: "Veuillez approuver l'accès à vos bêtes...",
    de: "Keur de toegang tot je Beasts goed...",
    pl: "Zatwierdź dostęp do swoich Bestii...",
    ph: "Mangyaring aprubahan ang pag-access sa iyong mga Hayop ...",
  },
  approvalAllWarriors: {
    en: "Please approve access to your Warriors...",
    es: "Aprueba el acceso a tus Warriors...",
    cn: "请批准访问您的勇士...",
    pt: "Por favor, aprove o acesso aos seus guerreiros...",
    tr: "Lütfen Savaşçılarınıza erişimi onaylayın...",
    ru: "Пожалуйста, подтвердите доступ к своим Воинам...",
    fr: "Veuillez approuver l'accès à vos Warriors...",
    de: "Keur de toegang tot je Warriors goed...",
    pl: "Zatwierdź dostęp do swoich wojowników...",
    ph: "Mangyaring aprubahan ang pag-access sa iyong mga Mandirigma...",
  },
  revealWarriors: {
    en: "Reveal Warriors",
    es: "Revelar guerreros",
    cn: "揭示勇士",
    pt: "Revelar Guerreiros",
    tr: "Savaşçıları Göster",
    ru: "Выявить воинов",
    fr: "Révéler les guerriers",
    de: "Onthul krijgers",
    pl: "Ujawnij wojowników",
    ph: "Ipakita ang mga Mandirigma",
  },
  revealBeasts: {
    en: "Reveal Beasts",
    es: "Revelar bestias",
    cn: "揭示野兽",
    pt: "Revelar Bestas",
    tr: "Canavarları Göster",
    ru: "Раскрыть зверей",
    fr: "Révéler les bêtes",
    de: "Beesten onthullen",
    pl: "Ujawnij bestie",
    ph: "Magbunyag ng mga Hayop",
  },
  revealingWarriors: {
    en: "Revealing Warriors...",
    es: "Revelando guerreros...",
    cn: "揭示勇士...",
    pt: "Revelando guerreiros...",
    tr: "Savaşçıları Ortaya Çıkarmak...",
    ru: "Раскрытие воинов...",
    fr: "Révéler les Guerriers...",
    de: "Onthullende krijgers...",
    pl: "Ujawnianie wojowników...",
    ph: "Pagbubunyag ng mga Mandirigma...",
  },
  revealingBeasts: {
    en: "Revealing Beasts...",
    es: "Bestias reveladoras...",
    cn: "揭露野兽...",
    pt: "Revelando Bestas...",
    tr: "Canavarları Ortaya Çıkarmak...",
    ru: "Раскрытие зверей...",
    fr: "Révéler les bêtes...",
    de: "Beesten onthullen...",
    pl: "Ujawnianie bestii...",
    ph: "Pagbubunyag ng mga Hayop...",
  },
  revealTextWarriors: {
    en: "You need to reveal warriors to see them.",
    es: "Necesitas revelar guerreras para verlas.",
    cn: "你需要揭示战士才能看到他们。",
    pt: "Você precisa revelar guerreiros para vê-los.",
    tr: "Onları görmek için savaşçıları ortaya çıkarmanız gerekiyor.",
    ru: "Вам нужно раскрыть воинов, чтобы увидеть их.",
    fr: "Vous devez révéler des guerriers pour les voir.",
    de: "Je moet krijgers onthullen om ze te zien.",
    pl: "Aby ich zobaczyć, musisz odsłonić wojowników.",
    ph: "Kailangan mong ipakita ang mga mandirigma para makita sila.",
  },
  revealTextBeasts: {
    en: "You need to reveal beasts to see them.",
    es: "Necesitas revelar bestias para verlas.",
    cn: "你需要揭示野兽才能看到它们。",
    pt: "Você precisa revelar bestas para vê-los.",
    tr: "Onları görmek için canavarları ortaya çıkarmanız gerekiyor.",
    ru: "Вам нужно раскрыть зверей, чтобы увидеть их.",
    fr: "Vous devez révéler les bêtes pour les voir.",
    de: "Je moet beesten onthullen om ze te zien.",
    pl: "Aby je zobaczyć, musisz odsłonić bestie.",
    ph: "Kailangan mong magbunyag ng mga hayop upang makita sila.",
  },
  revealResult: {
    en: "Reveal Result",
    es: "Revelar resultado",
    cn: "显示结果",
    pt: "Revelar resultado",
    tr: "Sonucu Göster",
    ru: "Показать результат",
    fr: "Révéler le résultat",
    de: "Resultaat onthullen",
    pl: "Ujawnij wynik",
    ph: "Ibunyag ang Resulta",
  },
  showNew: {
    en: "Show Only New",
    es: "Mostrar solo nuevos",
    cn: "只显示新的",
    pt: "Mostrar apenas novo",
    tr: "Yalnızca Yenileri Göster",
    ru: "Показать только новые",
    fr: "Afficher uniquement les nouveautés",
    de: "Toon alleen nieuw",
    pl: "Pokaż tylko nowe",
    ph: "Ipakita Lamang ang Bago",
  },
  unlockStatus: {
    en: "Unlock Status",
    es: "Estado de desbloqueo",
    cn: "解锁状态",
    pt: "Status de desbloqueio",
    tr: "Kilit Açma Durumu",
    ru: "Разблокировать статус",
    fr: "Déverrouiller l'état",
    de: "Ontgrendelstatus",
    pl: "Status odblokowania",
    ph: "I-unlock ang Katayuan",
  },
  warriorsUsed: {
    en: "Warriors Used",
    es: "guerreros usados",
    cn: "使用的勇士",
    pt: "Guerreiros usados",
    tr: "Kullanılan Savaşçılar",
    ru: "Используемые воины",
    fr: "Guerriers utilisés",
    de: "Gebruikte krijgers",
    pl: "Używani wojownicy",
    ph: "Mga Mandirigma na Ginamit",
  },
  plzRevealBeast: {
    en: "You have summoned Beasts! Go to the Beasts page to reveal them.",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
  plzRevealWarrior: {
    en: "You have summoned Warriors! Go to the Warriors page to reveal them.",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
  selectAll: {
    en: "Select All",
    es: "Seleccionar todo",
    cn: "全选",
    pt: "Selecionar tudo",
    tr: "Hepsini seç",
    ru: "Выбрать все",
    fr: "Tout sélectionner",
    de: "Selecteer alles",
    pl: "Zaznacz wszystko",
    ph: "Piliin lahat",
  },
  deSelectAll: {
    en: "Deselect All",
    es: "Deseleccionar todo",
    cn: "取消全選",
    pt: "Desmarcar todos",
    tr: "Tüm seçimleri kaldır",
    ru: "Убрать выделение со всего",
    fr: "Tout déselectionner",
    de: "Deselecteer alles",
    pl: "Odznacz wszystkie",
    ph: "Alisin sa pagkakapili ang Lahat",
  },
  warning: {
    en: "Warning!",
    es: "Advertencia!",
    cn: "警告！",
    pt: "Aviso!",
    tr: "Uyarı!",
    ru: "Предупреждение!",
    fr: "Avertissement!",
    de: "Avertissement!",
    pl: "Waarschuwing!",
    ph: "Babala!",
  },
  executeItem: {
    en: "You are about to execute items between level 3-6. Are you sure you want to go ahead?",
    es: "Está a punto de ejecutar elementos entre el nivel 3-6. ¿Estás seguro de que quieres seguir adelante?",
    cn: "您即将执行 3-6 级之间的项目。你确定要继续吗？",
    pt: "Você está prestes a executar itens entre o nível 3-6. Tem certeza de que quer ir em frente?",
    tr: "Seviye 3-6 arasındaki öğeleri yürütmek üzeresiniz. Devam etmek istediğinden emin misin?",
    ru: "Вы собираетесь выполнять предметы между уровнями 3-6. Вы уверены, что хотите продолжить?",
    fr: "Vous êtes sur le point d'exécuter des éléments entre les niveaux 3 et 6. Êtes-vous sûr de vouloir continuer ?",
    de: "Je staat op het punt om items tussen niveau 3-6 uit te voeren. Weet je zeker dat je door wilt gaan?",
    pl: "Masz zamiar wykonać przedmioty między poziomami 3-6. Czy na pewno chcesz kontynuować?",
    ph: "Ipapatupad mo na ang mga item sa pagitan ng level 3-6. Sigurado ka bang gusto mong magpatuloy?",
  },
  execute: {
    en: "Execute",
    es: "Ejecutar",
    cn: "执行",
    pt: "Executar",
    tr: "Uygulamak",
    ru: "Выполнять",
    fr: "Exécuter",
    de: "uitvoeren",
    pl: "Wykonać",
    ph: "Ipatupad",
  },
  moreCoin: {
    en: "You need more $BLST to summon.",
    es: "Necesitas más $BLST para convocar.",
    cn: "你需要更多的 $BLST 才能召唤.",
    pt: "Você precisa de mais $BLST para invocar.",
    tr: "Çağırmak için daha fazla $BLST'ye ihtiyacınız var.",
    ru: "Вам нужно больше $BLST для призыва.",
    fr: "Vous avez besoin de plus de $BLST pour invoquer.",
    de: "Je hebt meer $BLST nodig om op te roepen.",
    pl: "Do przywołania potrzebujesz więcej $BLST.",
    ph: "Kailangan mo ng higit pang $BLST para ipatawag.",
  },
  shareYourSuccess: {
    en: "Share Your Success!",
    es: "¡Comparta su éxito!",
    cn: "分享您的成功！",
    pt: "Compartilhe seu sucesso!",
    tr: "Başarını Paylaş!",
    ru: "Поделитесь своим успехом!",
    fr: "Partagez votre succès !",
    de: "Deel uw succes!",
    pl: "Podziel się swoim sukcesem!",
    ph: "Ibahagi ang Iyong Tagumpay!",
  },
  shareYourHappiness: {
    en: "Share Your Happiness!",
    es: "¡Comparte tu felicidad!",
    cn: "分享你的快乐!",
    pt: "Compartilhe sua felicidade!",
    tr: "Mutluluğunu Paylaş!",
    ru: "Поделись своим счастьем!",
    fr: "Partagez votre bonheur!",
    de: "Deel je geluk!",
    pl: "Dzielić swoje szczęście!",
    ph: "Ibahagi ang Iyong Kaligayahan!",
  },
  gotUnclaimedReward: (BLST, BUSD) => {
    return {
      en: `You just got ${BLST} $BLST (= ${BUSD} USD) in your wallet.`,
      es: `Acabas de recibir ${BLST} $BLST (= ${BUSD} USD) en tu billetera.`,
      cn: `你的钱包里刚刚有 ${BLST} $BLST (= ${BUSD} USD)。`,
      pt: `Você acabou de receber ${BLST} $BLST (= ${BUSD} USD) em sua carteira.`,
      tr: `Cüzdanınızda ${BLST} $BLST (= ${BUSD} USD) var.`,
      ru: `Вы только что получили ${BLST} $BLST (= ${BUSD} USD) на свой кошелек.`,
      fr: `Vous venez d'avoir ${BLST} $BLST (= ${BUSD} USD) dans votre portefeuille.`,
      de: `U heeft zojuist ${BLST} $BLST (= ${BUSD} USD) in uw portemonnee gekregen.`,
      pl: `Właśnie masz w portfelu ${BLST} $BLST (= ${BUSD} USD).`,
      ph: `Kakakuha mo lang ng ${BLST} $BLST (= ${BUSD} USD) sa iyong wallet.`,
    };
  },
  tips: {
    en: "Tips & Tricks",
    es: "consejos y trucos",
    cn: "提示与技巧",
    pt: "dicas e truques",
    tr: "İpuçları & Hileler",
    ru: "Советы и хитрости",
    fr: "Conseils & Astuces",
    de: "tips & trucs",
    pl: "Porady & Triki",
    ph: "Mga Tip at Trick",
  },
  hunthistory: {
    en: "Hunt History",
    es: "Historial de caza",
    cn: "狩猎历史",
    pt: "Histórico de caça",
    tr: "Av Tarihi",
    ru: "История охоты",
    fr: "Historique de la chasse",
    de: "Jachtgeschiedenis",
    pl: "Historia polowań",
    ph: "Kasaysayan ng Hunt",
  },
  loadmore: {
    en: "Load More",
    es: "Carga más",
    cn: "装载更多",
    pt: "Carregue mais",
    tr: "Daha fazla yükle",
    ru: "Загрузи больше",
    fr: "Charger plus",
    de: "Meer laden",
    pl: "Załaduj więcej",
    ph: "Mag-load ng Higit Pa",
  },
  nohistory: {
    en: "No hunt history found.",
    es: "No se ha encontrado ningún historial de caza.",
    cn: "未找到狩猎记录。",
    pt: "Nenhum histórico de caça encontrado.",
    tr: "Av geçmişi bulunamadı.",
    ru: "История охоты не найдена.",
    fr: "Aucun historique de chasse trouvé.",
    de: "Geen jachtgeschiedenis gevonden.",
    pl: "Nie znaleziono historii polowań.",
    ph: "Walang nakitang kasaysayan ng pangangaso.",
  },
  gohuntmore: {
    en: "Go hunt more!",
    es: "¡Ve a cazar más!",
    cn: "多打猎！",
    pt: "Vá caçar mais!",
    tr: "Git daha fazla avla!",
    ru: "Иди охотись еще!",
    fr: "Allez chasser plus!",
    de: "Ga meer jagen!",
    pl: "Idź polować więcej!",
    ph: "Manghuli pa!",
  },
  leaderboard: {
    en: "LeaderBoard",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
  summonLegionSuccessful: {
    en: "Your Legion is created.",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
  referral: {
    en: "Referral Program",
    es: "Programa de referencia",
    cn: "推荐计划",
    pt: "Programa de referência",
    tr: "Yönlendirme Programı",
    ru: "Реферальная программа",
    fr: "Programme de parrainage",
    de: "Empfehlungsprogramm",
    pl: "Program Polecający",
    ph: "Referral Program",
  },
  updateLegionSuccessful: {
    en: "Your Legion is updated.",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
};
